### PR TITLE
[e2e] Delete Service if WaitServiceExposureAndValidateConnectivity() fails

### LINKED ISSUE #4137: Some e2e tests don't have Service cleanup in defer function
#### Which jobs are flaking:
All ccm e2e jobs. It is not "flaking" but if some condition meets, errors will happen.

#### Which test(s) are flaking:
E.g. "should support BYO public IP"
There's no defer cleanup after the Service creation logic. If there's something wrong with the creation, the Service won't be deleted but those PIPs will. As a result, error like below will happen:
```
  Jun 20 08:23:30.804: INFO: error: network.PublicIPAddressesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="PublicIPAddressCannotBeDeleted" Message="Public IP
 address /subscriptions/xxx/resourceGroups/zhecheng-ipv4-md2/providers/Microsoft.Network/publicIPAddresses/service-lb-public-IP8f57 can not be deleted since i
t is still allocated to resource /subscriptions/xxx/resourceGroups/zhecheng-ipv4-md2/providers/Microsoft.Network/loadBalancers/zhecheng-ipv4-md2/frontendIPCon
figurations/a5502f744f5a244ef92713d8d27ed14d. In order to delete the public IP, disassociate/detach the Public IP address from the resource.  To learn how to do this, see aka.ms/deletepublici
p." Details=[], will retry soon [/home/zhechengli/github.com/lzhecheng/cloud-provider-azure/tests/e2e/utils/network_utils.go:409]
```

#### Reason for failure:
Frontend IP configuration of a Service are not removed before PIPs are removed.

Solution: Add a Service cleanup in defer function after those PIP defer cleanup function.

#### Anything else we need to know:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

### PR DESCRIPTION
**Pull request by lzhecheng**
#### What type of PR is this?
/kind testing

#### What this PR does / why we need it:
[e2e] Delete Service if WaitServiceExposureAndValidateConnectivity() fails
#### Which issue(s) this PR fixes:

Fixes #4137

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: tests/e2e/utils/service_utils.go [hunk 1]
```diff
@@ -100,20 +102,29 @@ func WaitServiceExposureAndGetIPs(cs clientset.Interface, namespace string, name
 }
 
 // WaitServiceExposureAndValidateConnectivity returns IPs of the service and check the connectivity if they are public IPs.
+// Service should have been created before calling this function.
 func WaitServiceExposureAndValidateConnectivity(cs clientset.Interface, ipFamily IPFamily, namespace string, name string, targetIPs []string) ([]string, error) {
 	var service *v1.Service
 	var err error
 	var ips []string
 
+	deleteService := func() {
```
Comment (MartinForReal) [inline tests/e2e/utils/service_utils.go:111]: how about invoke delete service in deferred funcions
```go
defer func() {
  if err != nil {
	err := DeleteService(cs, namespace, name)
	Expect(err).NotTo(HaveOccurred())
   }
}
```

Comment (MartinForReal) [reply tests/e2e/utils/service_utils.go:111]: we need to name the returned error as err

Comment (MartinForReal) [reply tests/e2e/utils/service_utils.go:111]: another approach would be errorgroup

Comment (jwtty) [inline tests/e2e/utils/service_utils.go:111]: You can also make deleteService is a deferred function. When err is not nil, delete the service.

Comment (lzhecheng) [reply tests/e2e/utils/service_utils.go]: Thank you. Updated.

Comment (lzhecheng) [reply tests/e2e/utils/service_utils.go]: Thank you. Updated.
