### PR TITLE
fix(loadbalancer): invalidate PIP cache on external LB frontend IP config changes

### LINKED ISSUE #9729: Found many ETag mismatch erros when updating public IPs
#### Which jobs are flaking:

Example: https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/9723/pull-cloud-provider-azure-e2e-ccm-vmss-ip-lb-capz-1-33/1997713865999126528/artifacts/clusters/capz-uhx40o/kube-system/cloud-controller-manager-7884f88595-9gzzv/cloud-controller-manager.log

W1207 18:27:04.239343       1 azure_publicip_repo.go:55] NetworkClientFactory.GetPublicIPAddressClient().CreateOrUpdate(capz-uhx40o, service-public-IP-83e8) failed: PUT https://management.azure.com/subscriptions/46678f10-4bbb-447e-98e8-d2829589f2d8/resourceGroups/capz-uhx40o/providers/Microsoft.Network/publicIPAddresses/service-public-IP-83e8
--------------------------------------------------------------------------------
RESPONSE 412: 412 Precondition Failed
ERROR CODE: PreconditionFailed
--------------------------------------------------------------------------------
{
  "error": {
    "code": "PreconditionFailed",
    "message": "Precondition failed.",
    "details": [
      {
        "code": "PreconditionFailedEtagMismatch",
        "message": "Etag provided in if-match header W/\"e22bbdab-2eaa-4075-bca2-b09547f3022e\" does not match etag W/\"38f5dcce-46aa-42a5-aed7-4e7777d5c28d\" of resource /subscriptions/46678f10-4bbb-447e-98e8-d2829589f2d8/resourceGroups/capz-uhx40o/providers/Microsoft.Network/publicIPAddresses/service-public-IP-83e8 in NRP data store."
      }
    ]
  }
}

#### Anything else we need to know:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

### PR DESCRIPTION
**Pull request by Liunardy**
#### What type of PR is this?
/kind bug
/kind flake

#### What this PR does / why we need it:
When a load balancer (LB) is reconciled and it changes its `frontendIPConfig`, the associated public IP (PIP) will also be updated which causes its etag to change. The following will reproduce PreconditionFailed error when doing `CreateOrUpdatePIP`:
1. create a user-assigned PIP.
1. create "old" service with dns label and ip annotation for the PIP.
1. delete the "old" service.
1. create a "new" service with the same annotation.
1. patch the "new" service dns label annotation.

`ensurePublicIPExists` has `changed` variable to track PIP changes. On the steps above, when creating the "new" service with the user-assigned PIP and the same DNS name, `changed` will be false. But LB will update its `frontendIPConfig` which affects the PIP to change the etag. The PIP etag is now stale.
When updating the "new" service to use a different DNS name, `changed` will be true and it updates using the stale etag which will result in this error.

This PR invalidates the PIP cache if external load balancer changes its `frontendIPConfig` and adds the corresponding unit tests. It also corrects the E2E DNS validation after a service changes its DNS annotation.

#### Which issue(s) this PR fixes:

Fixes #9729

#### Does this PR introduce a user-facing change?

```release-note
fix: invalidate PIP cache on external LB frontend IP config changes
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nilo19** [comment]
@Liunardy can you go through our ci logs to make sure there is no pip etag errors?

**Comment by Liunardy** [comment]
> @Liunardy can you go through our ci logs to make sure there is no pip etag errors?

Found pip etag errors in https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/9859/pull-cloud-provider-azure-e2e-ccm-vmss-multi-slb-capz/2013763749122412544. Will look into this one.
The others don't have pip etag errors.

File: pkg/provider/azure_loadbalancer.go [hunk 1]
```diff
@@ -2017,6 +2017,15 @@ func (az *Cloud) reconcileLoadBalancer(ctx context.Context, clusterName string,
...
 
 			addOrUpdateLBInList(&existingLBs, newLB)
+
+			// Invalidate PIP cache only when external LB's frontend IP config is changed
+			// because LB updates modify pip.properties.ipConfiguration.id which changes the PIP etag.
+			// Internal LB changes (subnet/private IP) don't affect PIPs.
+			if fipChanged && !requiresInternalLoadBalancer(service) {
+				pipResourceGroup := az.getPublicIPAddressResourceGroup(service)
+				_ = az.pipCache.Delete(pipResourceGroup)
+				logger.V(2).Info("Invalidated PIP cache due to frontend IP config changes in lb", "lbName", lbName, "pipResourceGroup", pipResourceGroup)
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go]: better set to 4 or 5.

File: tests/e2e/network/service_annotations.go [hunk 2]
```diff
@@ -247,7 +247,7 @@ var _ = Describe("Service with annotation", Label(utils.TestSuiteLabelServiceAnn
 		_, err = cs.CoreV1().Services(ns.Name).Update(context.TODO(), service, metav1.UpdateOptions{})
 		Expect(err).NotTo(HaveOccurred())
 
-		serviceDomainName = utils.GetServiceDomainName(serviceDomainNamePrefix)
+		serviceDomainName = utils.GetServiceDomainName(fmt.Sprintf("%s-new", serviceDomainNamePrefix))
```
Comment (nilo19) [inline tests/e2e/network/service_annotations.go]: can we extract this as a new variable?

File: pkg/provider/azure_loadbalancer.go [hunk 3]
```diff
@@ -2017,6 +2017,15 @@ func (az *Cloud) reconcileLoadBalancer(ctx context.Context, clusterName string,
 			lb = newLB
 
 			addOrUpdateLBInList(&existingLBs, newLB)
+
+			// Invalidate PIP cache only when external LB's frontend IP config is changed
+			// because LB updates modify pip.properties.ipConfiguration.id which changes the PIP etag.
+			// Internal LB changes (subnet/private IP) don't affect PIPs.
+			if fipChanged && !requiresInternalLoadBalancer(service) {
+				pipResourceGroup := az.getPublicIPAddressResourceGroup(service)
+				_ = az.pipCache.Delete(pipResourceGroup)
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go]: I know we have many similiar code but it's not a good pattern to ignore returned errors. Maybe we can log the error for debugging purpose.

File: pkg/provider/azure_loadbalancer.go (hunk 1 above)
Comment (Liunardy) [reply pkg/provider/azure_loadbalancer.go]: Set to 5.

File: tests/e2e/network/service_annotations.go (hunk 2 above)
Comment (Liunardy) [reply tests/e2e/network/service_annotations.go]: Extracted as `newServiceDomainNamePrefix`.

File: pkg/provider/azure_loadbalancer.go (hunk 3 above)
Comment (Liunardy) [reply pkg/provider/azure_loadbalancer.go]: Logged the error.

**Comment by nilo19** [comment]
please add release note: fix: invalidate PIP cache on external LB frontend IP config changes

File: pkg/provider/azure_loadbalancer_test.go [hunk 4]
```diff
@@ -4115,12 +4328,60 @@ func TestReconcileLoadBalancerCommon(t *testing.T) {
...
+				mockSubnetRepo := az.subnetRepo.(*subnet.MockRepository)
+				mockSubnetRepo.EXPECT().Get(gomock.Any(), "rg", "vnet", "subnet").Return(&armnetwork.Subnet{
+					ID:   ptr.To("/subscriptions/subscription/resourceGroups/rg/providers/Microsoft.Network/virtualNetworks/vnet/subnets/subnet"),
+					Name: ptr.To("subnet"),
+				}, nil).AnyTimes()
+			}
+
+			// Populate PIP cache before reconciliation to test cache invalidation.
+			pipResourceGroup := az.getPublicIPAddressResourceGroup(&service)
+			pips, _ := az.listPIP(context.TODO(), pipResourceGroup, 0)
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer_test.go]: prefer cache.CacheReadTypeDefault over 0 for readability

**Comment by nilo19** [comment]
Consider adding a unit test comment explaining why internal LB tests are included (to verify NO cache invalidation happens for internal LBs)

**Comment by Liunardy** [comment]
> > @Liunardy can you go through our ci logs to make sure there is no pip etag errors?
> 
> Found pip etag errors in https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/9859/pull-cloud-provider-azure-e2e-ccm-vmss-multi-slb-capz/2013763749122412544. Will look into this one. The others don't have pip etag errors.

Checked the latest CIs and it has the same PIP etag errors for multi-slb CI: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/9859/pull-cloud-provider-azure-e2e-ccm-vmss-multi-slb-capz/2014159393792200704. The others don't have pip etag errors.

The E2E scenarios that hit this are the same:
- Network security group when creating 2 LoadBalancer services with shared public IP should add rules independently
- Ensure LoadBalancer should support multiple external services sharing one newly created public IP addresses

The pattern also looks similar in ccm log before hitting this error. For example:
- "change the LB to another one" logger="shouldChangeLoadBalancer" service="service-lb-test-1" currLBName="capz-gweako" clusterName="capz-gweako" expectedLBName="lb-1"
- "deleting load balancer because there is no remaining frontend IP configurations" logger="removeFrontendIPConfigurationFromLoadBalancer" lbName="capz-gweako" fipNames=["ad91ba9a2f1c845c5bf3c6443f43219e"] clusterName="capz-gweako" serviceName="service-lb-test-1"

Other CIs that run those 2 don't have PIP etag error. I think this is unique to multi-SLB scenario.

File: pkg/provider/azure_loadbalancer_test.go (hunk 4 above)
Comment (Liunardy) [reply pkg/provider/azure_loadbalancer_test.go]: Used the constant.
