### PR TITLE
fix: wait for the success of the initial run of syncRegionZonesMap

### LINKED ISSUE #640: Errors are not logged when zones map refreshed failed
**What happened**:

Refer the below error:

```
W0525 19:27:27.819483       1 azure_zones.go:52] refreshZones: error when get zones, will retry after 30m0s
W0525 19:57:27.953782       1 azure_zones.go:52] refreshZones: error when get zones, will retry after 30m0s
W0525 20:27:27.734746       1 azure_zones.go:52] refreshZones: error when get zones, will retry after 30m0s
```

**What you expected to happen**:

- Detailed errors should be logged in logs message
- Cloud provider should wait for the first zone map refresh finish on initialization

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/bfc60a7659c734a293baa6d8f96ce56afa8a07b1/pkg/provider/azure.go#L503

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by nilo19**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind cleanup

**What this PR does / why we need it**:

1. Log detailed error messages in `syncRegionZonesMap`;
2. Wait for the initial run of `syncRegionZonesMap` to be successful.
3. Disable the zone sync operation in cnm, only enable it in ccm.

**Which issue(s) this PR fixes**:

Fixes #640

**Special notes for your reviewer**:

**Release note**:
```
fix: wait for the success of the initial run of syncRegionZonesMap
```

### CODE REVIEW

File: pkg/provider/azure.go [hunk 1]
```diff
@@ -532,6 +532,13 @@ func (az *Cloud) InitializeCloudFromConfig(config *Config, fromSecret bool) erro
 	az.routeUpdater = newDelayedRouteUpdater(az, routeUpdateInterval)
 	go az.routeUpdater.run()
 
+	// wait for the success first time of syncing zones
+	err = az.syncRegionZonesMap()
```
Comment (andyzhangx) [inline pkg/provider/azure.go:536]: may be not related to this PR:  is there a way to turn off `syncRegionZonesMap`? e.g. for agent node driver, it would invoke `InitializeCloudFromConfig`, while it's not necessary to run `syncRegionZonesMap` since in most cases agent node does not have permission.

Comment (feiskyer) [reply pkg/provider/azure.go:536]: agreed, let's add a new property to allow it's to be disabled. it should only be enabled inside the controller and should be disabled by default in nodes.

Comment (nilo19) [reply pkg/provider/azure.go:536]: We need to know the zone info in node-manager. For example: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/67ab70534c99da15b3ec1a6c0b55d352fe638a3b/pkg/node/nodearm.go#L92

**Comment by nilo19** [comment]
@feiskyer I think this one is ready.

File: pkg/provider/azure.go (hunk 1 above)
Comment (feiskyer) [reply pkg/provider/azure.go:536]: If IMDS is not disabled (which is the common case for most scenarios except azurestack), the zone info should be got from IMDS

Comment (feiskyer) [reply pkg/provider/azure.go:536]: I also see the same failure from unit tests, which caused unit test to run very slow until the requests timeout. We should disable it as well for most unit tests except the AZ tests

Comment (nilo19) [reply pkg/provider/azure.go]: Only enables the zone syncing in ccm now and disable it in cnm, please take a look again.

Comment (nilo19) [reply pkg/provider/azure.go]: For unit tests, I mock the zone client every time the `syncRegionZonesMap` is called, so there shouldn't be any timeouts.

File: pkg/provider/azure.go [hunk 2]
```diff
@@ -504,6 +535,34 @@ func (az *Cloud) InitializeCloudFromConfig(config *Config, fromSecret bool) erro
...
+		return err
+	}
+
+	if err := initDiskControllers(az); err != nil {
+		return err
+	}
+
+	// start delayed route updater.
+	az.routeUpdater = newDelayedRouteUpdater(az, routeUpdateInterval)
+	go az.routeUpdater.run()
```
Comment (feiskyer) [inline pkg/provider/azure.go:549]: we should also make routeUpdater as optional as it should not run on node manager. Let's do it in a follow up PR.

**Review by feiskyer — APPROVED** [review]
/lgtm
