### PR TITLE
fix(multi-slb): support IP sharing across multiple services

### LINKED ISSUE #9867: [Multi-SLB] support ip sharing across multiple services
#### What happened:

Service A has been created to use IP 1. Now we want to create a service B point to the same IP. During the lb selection phase of service B, it will select another LB with less existing services than service A's LB. Since the LB selected is a different one, LB migration logic will be triggered, and the service A's frontend IP config will be removed by accident.
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_loadbalancer.go#L846

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by Liunardy**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
In multi-SLB mode, when Service B shares an IP with existing Service A, `getAzureLoadBalancerName` picks the LB with the fewest rules instead of the LB where the IP resides. This triggers migration logic that accidentally removes Service A's frontend IP configuration. This fixes that by picking the LB where the IP resides.

Additional fixes:
- Block LB migration when it would remove a frontend IP shared with other services.
- Block conflicting LB config annotation when the service also specifies an IP.
- Block IP specification pointing to an ineligible LB.

#### Which issue(s) this PR fixes:

Fixes #9867

#### Does this PR introduce a user-facing change?

```release-note
fix(multi-slb): support IP sharing across multiple services

When a service specifies an IP address that already exists on a load balancer, the service is now placed on that load balancer instead of picking one with the fewest rules, provided the service is eligible for that load balancer. The load balancer configuration annotation cannot be combined with an IP specification. Migration to a different load balancer is blocked if the frontend IP is still referenced by other resources.

Switching internal/external issues (10050 and 10117) will be fixed in another change.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/provider/azure_loadbalancer.go [hunk 1]
```diff
@@ -4107,12 +4164,56 @@ func (az *Cloud) getAzureLoadBalancerName(
...
+		// If service specifies an IP, find which LB has that IP. The service should use the LB where the IP resides.
+		// This also detects secondary services sharing an IP with a primary service already on an LB.
+		if pinsIP {
+			if requiresInternalLoadBalancer(service) {
+				currentLBName = az.getLoadBalancerNameByPrivateIP(ctx, service, existingLBs)
+			} else {
+				currentLBName = az.getLoadBalancerNameByPublicIP(ctx, service, clusterName)
+			}
+			// Block service if the IP resides on an LB that's not eligible.
+			if currentLBName != "" && !StringInSlice(currentLBName, eligibleLBs) {
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go]: please ignore case here as we have ignored case in getLoadBalancerNameByPrivateIP.

File: pkg/provider/azure_loadbalancer.go [hunk 2]
```diff
@@ -807,10 +807,20 @@ func (az *Cloud) getServiceLoadBalancer(
 		existingLBs = lbs
 	}
 
+	// A service must use the LB that owns its IP. In IP-pinned multi-SLB scenario,
+	// The service may currently exist on a different LB needing migration,
+	// so all LBs should be scanned instead of returning on the first match.
+	lbIPs := getServiceLoadBalancerIPs(service)
+	pipNames := getServicePIPNames(service)
+	pinsIP := len(lbIPs) > 0 || lo.ContainsBy(pipNames, func(s string) bool { return s != "" })
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go]: can we move the empty check into getServicePIPNames?

File: pkg/provider/azure_loadbalancer.go [hunk 3]
```diff
@@ -843,6 +853,29 @@ func (az *Cloud) getServiceLoadBalancer(
...
+			// Block migration if the frontend IP is unsafe to delete
+			// (shared with other services, or referenced by outbound/NAT rules).
+			if az.UseMultipleStandardLoadBalancers() {
+				for _, fip := range fipConfigs {
+					unsafe, err := az.isFrontendIPConfigUnsafeToDelete(existingLB, service, fip.ID)
+					if err != nil {
+						return nil, nil, nil, nil, false, false, err
+					}
+					if unsafe {
+						logger.Info("Blocking load balancer migration because frontend IP is shared with other services",
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go]: according to the logging guide, don't emit an error log before returning an error. you may put the useful information into the error message.

File: pkg/provider/azure_loadbalancer.go (hunk 1 above)
Comment (Liunardy) [reply pkg/provider/azure_loadbalancer.go]: Added `StringInSliceIgnoreCase` function and used it here.

File: pkg/provider/azure_loadbalancer.go (hunk 2 above)
Comment (Liunardy) [reply pkg/provider/azure_loadbalancer.go]: Moved the check there and updated the unit test. Now it only returns list with non-empty string.

File: pkg/provider/azure_loadbalancer.go (hunk 3 above)
Comment (Liunardy) [reply pkg/provider/azure_loadbalancer.go]: Removed the log and added additional info (the LB to migrate to) into the error message.

File: pkg/provider/azure_loadbalancer.go [hunk 4]
```diff
@@ -825,7 +835,49 @@ func (az *Cloud) getServiceLoadBalancer(
 			return nil, nil, nil, nil, false, false, err
 		}
 		if status == nil {
-			// service is not on this load balancer
+			// Service is not on this LB by frontend IP ownership.
+			// However, if multi-SLB is enabled and the service should move to a
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go:839]: only for multi-slb? what if we remove the ip pin in single-slb mode?

Comment (nilo19) [reply pkg/provider/azure_loadbalancer.go:839]: ok, I don't think we have this bug for single-slb.

**Comment by nilo19** [comment]
If the service is the only secondary service, and moved to another LB, the stale frontend ip config won't be removed, thus the old pip cannot be removed as well.

File: pkg/provider/azure_loadbalancer.go [hunk 5]
```diff
@@ -825,7 +835,54 @@ func (az *Cloud) getServiceLoadBalancer(
...
+			// different LB, the old LB may still have stale rules/probes left
+			// from when the service shared a frontend IP. Remove them to
+			// prevent orphaned rules and probes on the old LB.
+			if wantLb && az.UseMultipleStandardLoadBalancers() &&
+				az.shouldChangeLoadBalancer(service, ptr.Deref(existingLB.Name, ""), clusterName, defaultLBName) &&
+				az.lbHasServiceOwnedResources(existingLB, service) {
+
+				deletedLBName, err := az.removeStaleServiceLBResources(ctx, existingLB, existingLBs, clusterName, service)
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go]: removeFrontendIPConfigurationFromLoadBalancer returns a deletedPLS bool. When a Private Link Service exists on the FIP, it exits early with deletedPLS=true without actually updating/deleting the LB. The existing migration path at L930 handles this correctly by returning early with deletedPLS=true to trigger a retry. But the new removeStaleServiceLBResources at L2622 ignores this signal entirely — it discards deletedPLS with _, err := and treats success as full completion.

File: pkg/provider/azure_loadbalancer.go [hunk 6]
```diff
@@ -4122,6 +4391,122 @@ func (az *Cloud) getAzureLoadBalancerName(
...
+	loadBalancerIPs := getServiceLoadBalancerIPs(service)
+	pipResourceGroup := az.getPublicIPAddressResourceGroup(service)
+	for _, ip := range loadBalancerIPs {
+		if ip == "" {
+			continue
+		}
+		pip, err := az.findMatchedPIP(ctx, ip, "", pipResourceGroup)
+		if err != nil {
+			logger.V(2).Info("Failed to find PIP by IP", "ip", ip, "error", err)
+			continue
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go]: why do we want to continue instead of returning an error?
this means if there is an error here (e.g., by a transient arm failure), it will sliently falling back to the generic fewest-rules chooser, which means the bug fix fixes nothing.

File: pkg/provider/azure_loadbalancer.go
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go]: not related to this fix but need to ignore case here as well, similiar with L4375.

File: pkg/provider/azure_loadbalancer.go [hunk 7]
```diff
@@ -4107,12 +4330,58 @@ func (az *Cloud) getAzureLoadBalancerName(
...
 			return "", err
 		}
 
 		currentLBName := az.getServiceCurrentLoadBalancerName(service)
+
+		// If service specifies an IP, find which LB has that IP. The service should use the LB where the IP resides.
+		// This also detects secondary services sharing an IP with a primary service already on an LB.
+		if pinsIP {
+			if requiresInternalLoadBalancer(service) {
+				currentLBName = az.getLoadBalancerNameByPrivateIP(ctx, service, existingLBs)
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go:4360]: we are 100% sure existingLBs cannot be empty, right? or it will fallback to existing lb selection logic which contains bug.

File: pkg/provider/azure_loadbalancer.go [hunk 8]
```diff
@@ -825,7 +835,54 @@ func (az *Cloud) getServiceLoadBalancer(
...
+				}
+
+				az.reconcileMultipleStandardLoadBalancerConfigurationStatus(
+					false,
+					getServiceName(service),
+					ptr.Deref(existingLB.Name, ""),
+				)
+
+				// Same backend pool cleanup as the normal LB migration path below.
+				if isLocalService(service) {
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go:872]: You removed deletedLBName != "" check, which seems to be harmless, as in this case cleanupLocalServiceBackendPool will be a no-op, but better have this check to keep aligned with the existing logics below.

File: pkg/provider/azure_loadbalancer.go [hunk 9]
```diff
@@ -825,7 +835,54 @@ func (az *Cloud) getServiceLoadBalancer(
...
+					svcName := getServiceName(service)
+					if az.backendPoolUpdater != nil {
+						az.backendPoolUpdater.removeOperation(svcName)
+					}
+					newLBs, err := az.cleanupLocalServiceBackendPool(ctx, service, nodes, existingLBs, clusterName)
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go]: have we tested this case either manually or by a test case?

File: pkg/provider/azure_loadbalancer.go [hunk 10]
```diff
@@ -825,7 +835,54 @@ func (az *Cloud) getServiceLoadBalancer(
...
+			// different LB, the old LB may still have stale rules/probes left
+			// from when the service shared a frontend IP. Remove them to
+			// prevent orphaned rules and probes on the old LB.
+			if wantLb && az.UseMultipleStandardLoadBalancers() &&
+				az.shouldChangeLoadBalancer(service, ptr.Deref(existingLB.Name, ""), clusterName, defaultLBName) &&
+				az.lbHasServiceOwnedResources(existingLB, service) {
+
+				deletedLBName, err := az.removeStaleServiceLBResources(ctx, existingLB, existingLBs, clusterName, service)
+				if err != nil {
+					logger.Error(err, "failed to remove stale service resources from old load balancer",
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go]: there are many places in this pr where you emit an error log before returning the error, this is not recommended as per logging conventions doc.

File: pkg/provider/azure_loadbalancer.go [hunk 11]
```diff
@@ -843,6 +900,24 @@ func (az *Cloud) getServiceLoadBalancer(
...
+			// (shared with other services, or referenced by outbound/NAT rules).
+			if az.UseMultipleStandardLoadBalancers() {
+				for _, fip := range fipConfigs {
+					unsafe, err := az.isFrontendIPConfigUnsafeToDelete(existingLB, service, fip.ID)
+					if err != nil {
+						return nil, nil, nil, nil, false, false, err
+					}
+					if unsafe {
+						return nil, nil, nil, nil, false, false, fmt.Errorf(
+							"service %q cannot migrate from load balancer %q to %q because frontend IP %q is shared with other services; "+
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go]: minor concern:  isFrontendIPConfigUnsafeToDelete can also report outbound/NAT rule references, making the message misleading.

File: pkg/provider/azure_loadbalancer.go (hunk 7 above)
Comment (Liunardy) [reply pkg/provider/azure_loadbalancer.go:4360]: getAzureLoadBalancerName receives existingLBs from getServiceLoadBalancer and selectLoadBalancer.

existingLBs is whatever the caller of getServiceLoadBalancer passes:
- reconcileLoadBalancer passes the result of ListManagedLBs. This can return empty only if no LBs exist yet. In empty case, this means no LB has the private IP yet because no LB exists. 
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/0f2687ccdf71e86f6cf07321f5bc3d10f2fd96e1/pkg/provider/azure_loadbalancer.go#L1839

- EnsureLoadBalancerDeleted passes empty existingLBs, but wantLb=false (I'm changing the LB lookup by IP to only be done if wantLB=true, so this skips)
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/0f2687ccdf71e86f6cf07321f5bc3d10f2fd96e1/pkg/provider/azure_loadbalancer.go#L476

- GetLoadBalancer and shouldUpdateLoadBalancer both pass wantLb=false, skipped
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/0f2687ccdf71e86f6cf07321f5bc3d10f2fd96e1/pkg/provider/azure_loadbalancer.go#L106
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/0f2687ccdf71e86f6cf07321f5bc3d10f2fd96e1/pkg/provider/azure_loadbalancer.go#L112
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/0f2687ccdf71e86f6cf07321f5bc3d10f2fd96e1/pkg/provider/azure_loadbalancer.go#L3295

selectLoadBalancer is only called for basic LB clusters. The multi-SLB LB lookup is never reached from this call.
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/0f2687ccdf71e86f6cf07321f5bc3d10f2fd96e1/pkg/provider/azure_loadbalancer.go#L896-L898

File: pkg/provider/azure_loadbalancer.go (hunk 5 above)
Comment (Liunardy) [reply pkg/provider/azure_loadbalancer.go]: Returned deletedPLS and added a test case for removeStaleServiceLBResources.

File: pkg/provider/azure_loadbalancer.go (hunk 6 above)
Comment (Liunardy) [reply pkg/provider/azure_loadbalancer.go]: Returned the error and only look up the LB if wantLb.

File: pkg/provider/azure_loadbalancer.go
Comment (Liunardy) [reply pkg/provider/azure_loadbalancer.go]: Ignored case in this function.

File: pkg/provider/azure_loadbalancer.go (hunk 8 above)
Comment (Liunardy) [reply pkg/provider/azure_loadbalancer.go:872]: Added the check.

File: pkg/provider/azure_loadbalancer.go (hunk 9 above)
Comment (Liunardy) [reply pkg/provider/azure_loadbalancer.go]: Added test case "remove backend pool when a local secondary service changes its load balancer".

File: pkg/provider/azure_loadbalancer.go (hunk 10 above)
Comment (Liunardy) [reply pkg/provider/azure_loadbalancer.go]: Removed the error log.

File: pkg/provider/azure_loadbalancer.go (hunk 11 above)
Comment (Liunardy) [reply pkg/provider/azure_loadbalancer.go]: Updated the reason to mention "also referenced by other resources". When user encountered this error, they'll see other events from isFrontendIPConfigUnsafeToDelete as well for example:

Warning DeletingFrontendIPConfiguration 6s azure-cloud-provider isFrontendIPConfigUnsafeToDelete: frontend IP configuration with ID [the id] on LB [the lb] cannot be deleted because it is being referenced by load balancing rules of other services

Warning  SyncLoadBalancerFailed 6s service-controller Error syncing load balancer: failed to ensure load balancer: service "[the svc]" cannot migrate from load balancer "[the lb from]" to "[the lb to]" because frontend IP "[the fip]" is also referenced by other resources; remove the service.beta.kubernetes.io/azure-load-balancer-configurations annotation to stay on load balancer "[the lb from]"

File: pkg/provider/azure_loadbalancer.go [hunk 12]
```diff
@@ -2074,7 +2167,12 @@ func (az *Cloud) reconcileLoadBalancer(ctx context.Context, clusterName string,
 		}
 	}
 
-	if fipChanged {
+	// Update multi-SLB ActiveServices tracking. Two signals indicate a real change:
+	//   - fipChanged: FIP added/removed (service is sole owner of its IP)
+	//   - lbRulesChanged: rules added/removed but FIP kept (shared-IP scenario)
+	// The "flipped" reconcile pass (wantLb=false for the opposite LB type)
+	// triggers neither, so it won't incorrectly remove the service.
+	if fipChanged || (az.UseMultipleStandardLoadBalancers() && lbRulesChanged) {
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go:2175]: in an non ip-sharing case where lbRulesChanged=truen fipChanged=false, there will be an extra operation to insert the svc into the lbconfig. but it would be harmless, right?

File: pkg/provider/azure_loadbalancer_test.go [hunk 13]
```diff
@@ -1940,579 +1940,1591 @@ func TestGetServiceLoadBalancerMultiSLB(t *testing.T) {
...
+			expectedError: fmt.Errorf(
+				"service %q cannot migrate from load balancer %q to %q because frontend IP %q is also referenced by other resources; "+
+					"remove the %s annotation to stay on load balancer %q",
+				"primary", "lb1", "lb2", "aprimary",
+				consts.ServiceAnnotationLoadBalancerConfigurations, "lb1"),
 		},
 		{
-			desc: "getServiceLoadBalancer should not change LB when names are the same but with different case with standard LB",
-			SKU:  consts.LoadBalancerSKUStandard,
+			description: "internal: block migration when primary svc shares IP with secondary",
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer_test.go:2181]: after this pr merges, can we enrich our doc as well to state the multi-slb ip-sharing behavior?

File: tests/e2e/network/multiple_standard_lb.go [hunk 14]
```diff
@@ -311,3 +1867,93 @@ func waitLBCountEqualTo(tc *utils.AzureTestClient, interval, timeout time.Durati
 	})
 	return lbNames, err
 }
+
+// waitForServiceEventAfter waits for an event of the given type on the service with the expected Reason
+// that occurred after the specified time and contains the expected message substring.
+func waitForServiceEventAfter(
```
Comment (nilo19) [inline tests/e2e/network/multiple_standard_lb.go]: can we move the utils funcs to service_utils.go?

**Comment by nilo19** [comment]
AI generated e2e overlap analysis:

image

File: pkg/provider/azure_loadbalancer.go (hunk 12 above)
Comment (Liunardy) [reply pkg/provider/azure_loadbalancer.go:2175]: Should be harmless when lbRulesChanged=true and fipChanged=false. For example, port change. SafeInsert existing service on a set is idempotent.

File: tests/e2e/network/multiple_standard_lb.go (hunk 14 above)
Comment (Liunardy) [reply tests/e2e/network/multiple_standard_lb.go]: Moved the service event and IP change funcs to tests/e2e/utils/service_utils.go

File: tests/e2e/network/multiple_standard_lb.go [hunk 15]
```diff
@@ -299,6 +1048,169 @@ func getLBsFromPublicIPs(tc *utils.AzureTestClient, pips []*string) sets.Set[str
 	return lbNames
 }
 
+// verifyFIPRemoved checks that the specified frontend IP configuration no longer exists on the LB.
+// Returns nil if the FIP is gone (or the entire LB is gone). Returns an error if the FIP still exists.
+func verifyFIPRemoved(tc *utils.AzureTestClient, fipID string) error {
```
Comment (nilo19) [inline tests/e2e/network/multiple_standard_lb.go]: could you please move the helpers to loadbalancer utils func?

**Comment by nilo19** [comment]
lgtm, thanks for the fix.

File: tests/e2e/network/multiple_standard_lb.go (hunk 15 above)
Comment (Liunardy) [reply tests/e2e/network/multiple_standard_lb.go]: Moved new lb/fip helpers, that can be easily moved, to utils.
