### PR TITLE
fix: decouple vmss with 0 instance from lb when deleting the service

### LINKED ISSUE #2443: Should remove LB backend pool reference from VMSS with 0 capacity when updating backend pool type to nodeIP
#### What happened:

We only decouple VMSS with non-zero capacity from the LB when updating from NIC to IP-based Load Balancer.

#### What you expected to happen:

VMSS with zero capacity should also be decoupled from the LB.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by nilo19**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

We parse the id of ipConfigs in the lb backend pool to determine what vmss are needed to be decoupled from the lb. But for those with 0 instance, they cannot be decoupled since there is no corresponding ipConfigs in the lb. This PR checks all cached vmss, if it is bound with the lb, we decouple it.

#### Which issue(s) this PR fixes:

Fixes #2443 

#### Does this PR introduce a user-facing change?

```release-note
fix: decouple vmss with 0 instance from lb when deleting the service
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/provider/azure_vmss_cache.go [hunk 1]
```diff
@@ -92,13 +92,11 @@ func (ss *ScaleSet) newVMSSCache() (*azcache.TimedCache, error) {
...
 					continue
 				}
-				if scaleSet.OrchestrationMode == "" || scaleSet.OrchestrationMode == compute.OrchestrationModeUniform {
-					localCache.Store(*scaleSet.Name, &vmssEntry{
-						vmss:          &scaleSet,
-						resourceGroup: resourceGroup,
-						lastUpdate:    time.Now().UTC(),
-					})
-				}
+				localCache.Store(*scaleSet.Name, &vmssEntry{
```
Comment (nilo19) [inline pkg/provider/azure_vmss_cache.go:95]: Cache all vmss instead of only uniform ones. I don't think this will break the logic of vmss flex but @zmyzheng can correct me.

File: pkg/provider/azure_vmssflex.go [hunk 2]
```diff
@@ -926,17 +926,7 @@ func (fs *FlexScaleSet) EnsureBackendPoolDeleted(service *v1.Service, backendPoo
 		}
 	}
 
-	// 1. Ensure the backendPoolID is deleted from the VMSS.
```
Comment (nilo19) [inline pkg/provider/azure_vmssflex.go:929]: Since we ensure all vmss are decoupled from the lb in azure_vmss.go, we don't need it here, right?

File: pkg/provider/azure_vmss_cache.go [hunk 3]
```diff
@@ -92,13 +92,11 @@ func (ss *ScaleSet) newVMSSCache() (*azcache.TimedCache, error) {
 					klog.Warning("failed to get the name of VMSS")
 					continue
 				}
-				if scaleSet.OrchestrationMode == "" || scaleSet.OrchestrationMode == compute.OrchestrationModeUniform {
```
Comment (andyzhangx) [inline pkg/provider/azure_vmss_cache.go:95]: this has changed the original vmss flex behavior  cc @zmyzheng

Comment (zmyzheng) [reply pkg/provider/azure_vmss_cache.go:95]: We should not save VMSS Flex into the vmssCache.
vmssCache is only used for vmss uniform (although the name is a little missleading)
The VMSS Flex cache is inside ss.flexScaleSet.vmssFlexCache

Comment (zmyzheng) [reply pkg/provider/azure_vmss_cache.go:95]: The main reason we need two different caches is because the vm list API is different between Uniform and Flex

File: pkg/provider/azure_vmssflex.go (hunk 2 above)
Comment (zmyzheng) [reply pkg/provider/azure_vmssflex.go:929]: I think we should still need it. Per AKS request, I will add another vmType == vmssflex for pure vmssflex cluster. In this case, we skip the node type check and only initialize FlexScaleSet ( similar to the pure standalone VM cluster).

File: pkg/provider/azure_vmss_cache.go (hunk 1 above)
Comment (zmyzheng) [reply pkg/provider/azure_vmss_cache.go:95]: This will break the logic.

File: pkg/provider/azure_vmss_cache.go (hunk 3 above)
Comment (nilo19) [reply pkg/provider/azure_vmss_cache.go]: Thanks for the review. I roll back the change and use flex cache to get all vmss. Can you help review again?

**Review by feiskyer — APPROVED** [review]
lgtm

File: pkg/provider/azure_vmss.go [hunk 4]
```diff
@@ -1678,22 +1678,76 @@ func getScaleSetAndResourceGroupNameByIPConfigurationID(ipConfigurationID string
...
+					klog.V(4).Infof("ensureBackendPoolDeletedFromVMSS: found vmss %s with backend pool %s, removing it", to.String(vmss.Name), backendPoolID)
+					vmssNamesMap[to.String(vmss.Name)] = true
+				}
+			}
+
+			return true
+		}
+
+		// Walk through all cached vmss, and find the vmss that contains the backendPoolID.
+		vmssUniformMap.Range(walk)
```
Comment (zmyzheng) [inline pkg/provider/azure_vmss.go:1747]: Maybe I missed something, who will use the result of the walk? Why do we need to go through both flex and uniform here?

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by andyzhangx** [comment]
/hold
hold a moment for other comments

File: pkg/provider/azure_vmss.go [hunk 5]
```diff
@@ -1678,22 +1678,76 @@ func getScaleSetAndResourceGroupNameByIPConfigurationID(ipConfigurationID string
...
+			var vmss *compute.VirtualMachineScaleSet
+			if vmssEntry, ok := value.(*vmssEntry); ok {
+				vmss = vmssEntry.vmss
+			} else if v, ok := value.(*compute.VirtualMachineScaleSet); ok {
+				vmss = v
+			}
+
+			// When vmss is being deleted, CreateOrUpdate API would report "the vmss is being deleted" error.
+			// Since it is being deleted, we shouldn't send more CreateOrUpdate requests for it.
+			if vmss.ProvisioningState != nil && strings.EqualFold(*vmss.ProvisioningState, consts.VirtualMachineScaleSetsDeallocating) {
```
Comment (nilo19) [inline pkg/provider/azure_vmss.go:1711]: test

File: pkg/provider/azure_vmss.go [hunk 6]
```diff
@@ -1678,22 +1678,76 @@ func getScaleSetAndResourceGroupNameByIPConfigurationID(ipConfigurationID string
...
+				klog.V(3).Infof("ensureBackendPoolDeletedFromVMSS: found vmss %s being deleted, skipping", to.String(vmss.Name))
+				return true
+			}
+			if vmss.VirtualMachineProfile.NetworkProfile.NetworkInterfaceConfigurations == nil {
```
[the remark this answers is not in the document]
Comment (nilo19) [reply pkg/provider/azure_vmss.go:1719]: Done

**Review by zmyzheng — APPROVED** [review]

**Comment by nilo19** [comment]
Need an LGTM.
