### PR TITLE
fix: exclude non-ready nodes from azure load balancer

### LINKED ISSUE #1194: Azure load balancer is never updated when node status changes
(this is the same as https://github.com/kubernetes/kubernetes/issues/108283)
### What happened?

Nodes that are no longer in the `Ready` state (i.e. due to a reboot) do not get removed from backend pools of Azure load balancers.

In the current code, a node gets removed from the backend pool of an Azure load balancer only if:

- it is labeled with `node.kubernetes.io/exclude-from-external-load-balancers` or
- it is labeled with `"kubernetes.azure.com/managed" ="false"`

This is due to https://github.com/kubernetes-sigs/cloud-provider-azure/issues/851, first merged in 1.23. ([1][2])

However with the above PR, nodes that are no longer ready (i.e. due to a reboot) do _not_ get removed backend pools of Azure load balancers, which consequently keep considering such nodes as valid backends.

[1] https://github.com/kubernetes-sigs/cloud-provider-azure/blob/507dd8975b175b4aa6f5e3bfcc2870ddacb91bd7/pkg/provider/azure.go#L1077-L1088
[2] https://github.com/kubernetes-sigs/cloud-provider-azure/blob/507dd8975b175b4aa6f5e3bfcc2870ddacb91bd7/pkg/provider/azure.go#L1204-L1222

### What did you expect to happen?

Nodes that are no longer in the `Ready` state should be removed from Azure load balancers. 

The (cloud-agnostic) cloud provider controller already updates the list of nodes to include in backend pools based on
- `node.kubernetes.io/exclude-from-external-load-balancers` label or
- node Status != Ready
```
func (s *Controller) getNodeConditionPredicate() NodeConditionPredicate {
	return func(node *v1.Node) bool {
		if _, hasExcludeBalancerLabel := node.Labels[v1.LabelNodeExcludeBalancers]; hasExcludeBalancerLabel {
			return false
		}

		// If we have no info, don't accept
		if len(node.Status.Conditions) == 0 {
			return false
		}
		for _, cond := range node.Status.Conditions {
			// We consider the node for load balancing only when its NodeReady condition status
			// is ConditionTrue
			if cond.Type == v1.NodeReady && cond.Status != v1.ConditionTrue {
				klog.V(4).Infof("Ignoring node %v with %v condition status %v", node.Name, cond.Type, cond.Status)
				return false
			}
		}
		return true
	}
}
```
(https://github.com/kubernetes/kubernetes/blob/b93fd35dd030519c24dd02f8bc2a7f873d2928cd/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L668-L688)

... and the result of that is passed over to cloud-specific code.

Azure-specific code ignores that piece of information when it comes to deleting nodes from a load balancer and uses its own logic introduced in https://github.com/kubernetes-sigs/cloud-provider-azure/issues/851. **We whould extend this logic to include node status changes.**

### How can we reproduce it (as minimally and precisely as possible)?

- Have a service backed by UDP server pods
- Have a cloud load balancer deployed in Azure pointing to the service in the previous point
- Dump the backend pools on azure side: `az network lb list -g $RESOURCE_GROUP`
- Reboot a node
- the Azure cloud provider code won't react to that node becoming `NotReady`; in particular it will not issue a DELETE operation in order to remove that node from the corresponding backend pool on the Azure load balancer. This is evident in the logs because this line does /not/ appear (while it does appear in kubernetes 1.22!):
```
I0221 13:23:05.213367       1 azure_loadbalancer.go:1143] reconcileLoadBalancer for service (e2e-k8s-service-load-balancer-with-pdb-new-2741/service-test)(true): lb backendpool - found unwanted node
ci-ln-2mnyxbb-002ac-9wktq-master-1, decouple it from the LB
```
- Dump again the backend pools on azure side: `az network lb list -g $RESOURCE_GROUP` and compare it with the previous output from the same command: the output is exactly the same, showing that the rebooting node didn't get removed from its backend pool.

### Anything else we need to know?

This causes high disruption times to PDB-based apps during upgrade jobs:
we went from about 5s in kubernetes 1.22 to about 13s with kubernetes 1.23, as reported in https://github.com/kubernetes/kubernetes/issues/108112

### Kubernetes version

since 1.23

### Cloud provider

Azure

### OS version

_No response_

### Install tools

_No response_

### Container runtime (CRI) and and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by ricky-rav**
/kind bug
/kind regression

#### What this PR does / why we need it:
This PR makes sure that nodes that are not in the ready state get removed from Azure load balancer backend pools.

#### Which issue(s) this PR fixes:
Fixes #1194

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
This looks like a good fix to the regression to me.  A node that is not ready isn't a good endpoint to include since it results in situations where requests to a service of type load balancer fails.

**Comment by deads2k** [comment]
/lgtm cancel

improvement noted on https://github.com/kubernetes/kubernetes/pull/108284#discussion_r813266818

**Comment by nilo19** [comment]
Will newly created nodes be excluded from the LB? I think their status would be NotReady at the beginning.

**Comment by ricky-rav** [comment]
@nilo19 in the case you describe, yes, it would be excluded at first, and then once it becomes ready it will be included by another call of `updateNodeCaches`, triggered by the local node informers. Do you have any concerns about this? Thanks!

File: pkg/provider/azure.go [hunk 1]
```diff
@@ -1220,3 +1230,12 @@ func (az *Cloud) ShouldNodeExcludedFromLoadBalancer(nodeName string) (bool, erro
 
 	return az.excludeLoadBalancerNodes.Has(nodeName), nil
 }
+
+func isNodeReady(node *v1.Node) bool {
+	for _, cond := range node.Status.Conditions {
+		if cond.Type == v1.NodeReady && cond.Status == v1.ConditionTrue {
```
Comment (feiskyer) [inline pkg/provider/azure.go:1236]: Could we also check whether this is a new node or not here (via "node.cloudprovider.kubernetes.io/uninitialized")? new node should not be removed so as to reduce number of ARM calls. 

https://github.com/kubernetes/cloud-provider/blob/5a236942a3ca6f0454bfcb979cc31207af4894b2/api/well_known_taints.go#L20-L24

Comment (ricky-rav) [reply pkg/provider/azure.go:1240]: Sure! I added a check in lines 1100 and 1054. Thanks!

**Comment by ricky-rav** [comment]
@nilo19 @feiskyer we eventually converged on a solution that:
- takes node status into account
- explicitly excludes nodes that were deleted from the cluster, which seemed to be neglected by the current code
https://github.com/kubernetes/kubernetes/pull/108284/files

@deads2k and I weren't quite sure of why we should add to load balancers newly-created nodes that are actually not ready  yet. Are there particular advantages for users? Load balancers with invalid backends won't work as expected, right? Are there any particular reasons behind this choice?

Thanks!

**Comment by feiskyer** [comment]
@ricky-rav it is because of [Azure request throttling](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/request-limits-and-throttling). Some provisioning tools would add new Nodes to SLB backend pool on initialization, to reduce throttling, those VMs shouldn't be removed from the backend pool.

**Review by feiskyer — APPROVED** [review]
Thanks for addressing the comments.

/lgtm
/approve

**Comment by nilo19** [comment]
@ricky-rav could you fix the verification failures?

**Review by feiskyer — COMMENTED** [review]
/lgtm
