### PR TITLE
fix public ip list call reduction

### LINKED ISSUE #2706: publicIP list calls are not successfully reduced
#### What happened:
PublicIPAddress List calls are not successfully reduced:
I1028 21:04:41.482802       1 azure_armclient.go:145] Send.sendRequest got response with ContentLength -1, StatusCode 200 and responseBody length 103248
I1028 21:04:41.490402       1 azure_backoff.go:338] PublicIPAddressesClient.List(...) success
W1028 21:04:41.490452       1 azure_standard.go:367] serviceOwnsFrontendIP: unexpected error when finding match public IP of the service ... with loadBalancerLP ...: findMatchedPIPByLoadBalancerIP: cannot find public IP with IP address ... in resource group ...
I1028 21:04:41.602206       1 azure_armclient.go:145] Send.sendRequest got response with ContentLength -1, StatusCode 200 and responseBody length 103248
I1028 21:04:41.612513       1 azure_backoff.go:338] PublicIPAddressesClient.List(...) success
W1028 21:04:41.612580       1 azure_standard.go:367] serviceOwnsFrontendIP: unexpected error when finding match public IP of the service ... with loadBalancerLP ...: findMatchedPIPByLoadBalancerIP: cannot find public IP with IP address ... in resource group ...
I1028 21:04:41.786204       1 azure_armclient.go:145] Send.sendRequest got response with ContentLength -1, StatusCode 200 and responseBody length 103248
I1028 21:04:41.792915       1 azure_backoff.go:338] PublicIPAddressesClient.List(...) success
W1028 21:04:41.792956       1 azure_standard.go:367] serviceOwnsFrontendIP: unexpected error when finding match public IP of the service ... with loadBalancerLP ...: findMatchedPIPByLoadBalancerIP: cannot find public IP with IP address ... in resource group ...

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by jwtty**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Original `pip = &pipList` does not modify the passed slice actually.

#### Which issue(s) this PR fixes:

Fixes #2706 

#### Does this PR introduce a user-facing change?

```release-note
Fix to reduce PublicIPAddress list arm calls
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/provider/azure_loadbalancer.go [hunk 1]
```diff
@@ -919,11 +919,18 @@ func (az *Cloud) determinePublicIPName(clusterName string, service *v1.Service,
 
 func (az *Cloud) findMatchedPIPByLoadBalancerIP(service *v1.Service, loadBalancerIP, pipResourceGroup string, pips *[]network.PublicIPAddress) (*network.PublicIPAddress, error) {
 	if pips == nil {
+		return nil, fmt.Errorf("findMatchedPIPByLoadBalancerIP: nil pip list passed")
+	} else if cap(*pips) == 0 {
+		// use capacity to check whether pip has been listed
```
Comment (lodrem) [inline pkg/provider/azure_loadbalancer.go:924]: Is it an implicit requirement when we call this function? It seems to be error-prone.

Comment (feiskyer) [reply pkg/provider/azure_loadbalancer.go:924]: why not using `len()` here? (`len()` is used in other places)

Comment (feiskyer) [reply pkg/provider/azure_loadbalancer.go:924]: do you think it makes sense to save the listed PIP in an in-memory cache instead of passing the pointer to other functions? e.g. something like vmss cache or vm cache?

File: pkg/provider/azure_loadbalancer.go [hunk 2]
```diff
@@ -919,11 +919,18 @@ func (az *Cloud) determinePublicIPName(clusterName string, service *v1.Service,
 
 func (az *Cloud) findMatchedPIPByLoadBalancerIP(service *v1.Service, loadBalancerIP, pipResourceGroup string, pips *[]network.PublicIPAddress) (*network.PublicIPAddress, error) {
 	if pips == nil {
```
[the remark this answers is not in the document]
Comment (jwtty) [reply pkg/provider/azure_loadbalancer.go:923]: this actually should not happen.

File: pkg/provider/azure_loadbalancer.go (hunk 1 above)
Comment (jwtty) [reply pkg/provider/azure_loadbalancer.go]: updated, thanks

File: pkg/provider/azure_loadbalancer.go [hunk 3]
```diff
@@ -919,11 +921,14 @@ func (az *Cloud) determinePublicIPName(clusterName string, service *v1.Service,
...
+		// this should not happen
+		return nil, fmt.Errorf("findMatchedPIPByLoadBalancerIP: nil pip list passed")
+	} else if *pips == nil {
```
Comment (lodrem) [inline pkg/provider/azure_loadbalancer.go:926]: Should it check the length? Empty slice does not equal `nil`.
```suggestion
	} else if len(*pips) == 0 {
```

Comment (jwtty) [reply pkg/provider/azure_loadbalancer.go:926]: If length is 0, that means we already listed pip but there isn't any. We check nil to decide whether to list pip.

Comment (lodrem) [reply pkg/provider/azure_loadbalancer.go:926]: > We check nil to decide whether to list pip.
should it be `if pip == nil`?

Comment (lodrem) [reply pkg/provider/azure_loadbalancer.go:926]: nil is a valid slice, and by convention we will use `nil` as an `empty slice`. I suggest we better don't distinguish them.

In this case, the type is `*[]T`, so why not:
- `pip == nil`: to list pip
- `len(*pip) == 0`: already list, but it's empty
- else

Comment (lodrem) [reply pkg/provider/azure_loadbalancer.go:926]: if so, could you please add some comments to the function in case the caller misuse `nil` and `[]T`?

Comment (jwtty) [reply pkg/provider/azure_loadbalancer.go:929]: Added comments to make it clear. Thanks

**Review by feiskyer — APPROVED** [review]
/lgtm
