### PR TITLE
fix: Skip VMSS VM update operations if the VMs are not in good state

### LINKED ISSUE #2356: Skip VMSS VM operations if the VMs are in deleting state
#### What happened:

VMSS VM operations will report an error `InstanceIdsListInstanceIdNotActiveVM ` if the VM is being deleted or has been deleted but our cache is not up-to-date. We should skip the VM in the following cases:
1. If the VM is already in deleting state, then skip all following PUT requests.
2. If the VM PUT error message contains InstanceIdsListInstanceIdNotActiveVM, then treat the error as succeeded (we need this because the caches in cloud provider may be outdated).

#### What you expected to happen:

When VMSS VMs are being deleted, the corresponding operations should be skipped, instead of reporting an error.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by nilo19**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

- Skip VMSS VM update operations when:
1. PUT request returns ParentResourceNotFound error;
2. PUT request returns InstanceIdsListInstanceIdNotActiveVM error;

- Set the retryAfter to 5s when PUT failed due to concurrent operation conflict.

#### Which issue(s) this PR fixes:

Fixes #2356

#### Does this PR introduce a user-facing change?

```release-note
fix: Skip VMSS VM update operations if the VMs are not in good state
fix: Set the retryAfter to 5s when PUT failed due to concurrent operation conflict.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/azureclients/vmssvmclient/azure_vmssvmclient.go [hunk 1]
```diff
@@ -503,6 +504,17 @@ func (c *Client) updateVMSSVMs(ctx context.Context, resourceGroupName string, VM
 		defer c.armClient.CloseResponse(ctx, resp.Response)
 		if resp.Error != nil {
 			klog.V(5).Infof("Received error in %s: resourceID: %s, error: %s", "vmssvm.put.request", resourceID, resp.Error.Error())
+
+			errMsg := resp.Error.Error().Error()
+			if strings.Contains(errMsg, consts.VmssVMNotActiveErrorMessage) {
+				klog.V(2).Info("VMSS VM is not active, skip updating it.")
```
Comment (feiskyer) [inline pkg/azureclients/vmssvmclient/azure_vmssvmclient.go:510]: Could you add resourceID in the log?

File: pkg/azureclients/vmssvmclient/azure_vmssvmclient.go [hunk 2]
```diff
@@ -503,6 +504,17 @@ func (c *Client) updateVMSSVMs(ctx context.Context, resourceGroupName string, VM
...
+				continue
+			}
+			if strings.Contains(errMsg, consts.ParentResourceNotFoundMessageCode) {
+				klog.V(2).Info("VMSS VM's parent resource is not found, skip updating it.")
```
Comment (feiskyer) [inline pkg/azureclients/vmssvmclient/azure_vmssvmclient.go:514]: same here

File: pkg/azureclients/vmssvmclient/azure_vmssvmclient.go (hunk 1 above)
Comment (nilo19) [reply pkg/azureclients/vmssvmclient/azure_vmssvmclient.go]: done

File: pkg/azureclients/vmssvmclient/azure_vmssvmclient.go (hunk 2 above)
Comment (nilo19) [reply pkg/azureclients/vmssvmclient/azure_vmssvmclient.go]: done

File: pkg/azureclients/vmssvmclient/azure_vmssvmclient.go [hunk 3]
```diff
@@ -503,6 +504,17 @@ func (c *Client) updateVMSSVMs(ctx context.Context, resourceGroupName string, VM
 		defer c.armClient.CloseResponse(ctx, resp.Response)
 		if resp.Error != nil {
 			klog.V(5).Infof("Received error in %s: resourceID: %s, error: %s", "vmssvm.put.request", resourceID, resp.Error.Error())
+
+			errMsg := resp.Error.Error().Error()
+			if strings.Contains(errMsg, consts.VmssVMNotActiveErrorMessage) {
+				klog.V(2).Infof("VMSS VM %s is not active, skip updating it.", resourceID)
+				continue
+			}
+			if strings.Contains(errMsg, consts.ParentResourceNotFoundMessageCode) {
```
Comment (feiskyer) [inline pkg/azureclients/vmssvmclient/azure_vmssvmclient.go:513]: Could you also skip the following error:

    "message": "Operation 'Put on Virtual Machine Scale Set VM Instance' is not allowed on Virtual Machine Scale Set 'aks-xxxx-vmss' since it is marked for deletion. For more information on your operations, please refer to https://aka.ms/activitylog."

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by feiskyer** [comment]
@nilo19 could you fix the lint errors?

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve
