### PR TITLE
fix: Invalidate VMSS cache after VMSS VM changes

### LINKED ISSUE #9728: Found many ETag mismatch errors when updating VMSS
#### Which jobs are flaking:

Example: https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/9714/pull-cloud-provider-azure-e2e-ccm-dualstack-vmss-capz-1-34/1996743052206542848/artifacts/clusters/capz-r33ugw/kube-system/cloud-controller-manager-5dc4fc96d7-6w487/cloud-controller-manager.log

E1205 01:11:04.836523       1 azure_vmss_repo.go:48] CreateOrUpdateVMSS: error CreateOrUpdate vmss(capz-r33ugw-mp-0): PUT https://management.azure.com/subscriptions/46678f10-4bbb-447e-98e8-d2829589f2d8/resourceGroups/capz-r33ugw/providers/Microsoft.Compute/virtualMachineScaleSets/capz-r33ugw-mp-0
--------------------------------------------------------------------------------
RESPONSE 412: 412 Precondition Failed
ERROR CODE: PreconditionFailed
--------------------------------------------------------------------------------
{
  "error": {
    "code": "PreconditionFailed",
    "message": "Etag provided in if-match header \"2\" does not match etag \"3\" of resource."
  }
}

#### Anything else we need to know:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

### PR DESCRIPTION
**Pull request by nilo19**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Updating VMSS instance won't update VMSS ETag directly, but will trigger some Azure internal VMSS operation, and the VMSS ETag will be updated by that operation. So we need to invalidate VMSS cache after VMSS VM changes to minimize the chance of precondition failed error when writing VMSS.

#### Which issue(s) this PR fixes:

Fixes #9728

#### Does this PR introduce a user-facing change?

```release-note
fix: Invalidate VMSS cache after VMSS VM changes
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/provider/azure_vmss.go [hunk 1]
```diff
@@ -191,6 +191,7 @@ func (ss *ScaleSet) getVMSS(ctx context.Context, vmssName string, crt azcache.Az
 		return nil, err
 	}
 	if vmss != nil {
+		logger.V(6).Info("getVMSS: fetched vmss from cache", "vmssName", vmssName, "etag", ptr.Deref(vmss.Etag, ""))
```
Comment (Liunardy) [inline pkg/provider/azure_vmss.go]: I don't think `getVMSS:` is needed here since logger is contextual. If we remove it, we can start message with a capital letter https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md#message-style-guidelines.

File: pkg/provider/azure_vmss.go [hunk 2]
```diff
@@ -1354,10 +1356,11 @@ func (ss *ScaleSet) ensureVMSSInPool(ctx context.Context, _ *v1.Service, nodes [
 		//    - when the vmss is updated, the vmss cache invalid
 		//    - when the vmss update failed, we want to get fresh-new vmss in the next round of update, especially for EtagMismatch error
 		defer func() {
+			logger.V(2).Info("invalidating vmss cache after update", "vmss", vmssName, "reason", "vmss pool update")
 			_ = ss.vmssCache.Delete(consts.VMSSKey)
```
Comment (Liunardy) [inline pkg/provider/azure_vmss.go:1360]: Log the error?

File: pkg/provider/azure_vmss.go [hunk 3]
```diff
@@ -1415,6 +1418,17 @@ func (ss *ScaleSet) ensureHostsInPool(ctx context.Context, service *v1.Service,
 		mc.ObserveOperationWithResult(isOperationSucceeded)
 	}()
 
+	// Track if any VM updates happened to invalidate vmss cache after all defers run
+	hasVMUpdates := false
+	defer func() {
+		if hasVMUpdates {
+			logger.V(2).Info("invalidating vmss cache after updating vms", "reason", "vmss vms updated")
+			if err := ss.vmssCache.Delete(consts.VMSSKey); err != nil {
+				logger.Error(err, "Failed to invalidate vmss cache")
```
Comment (Liunardy) [inline pkg/provider/azure_vmss.go]: Use Info since this doesn't return error.

File: pkg/provider/azure_vmss.go [hunk 4]
```diff
@@ -1498,6 +1513,10 @@ func (ss *ScaleSet) ensureHostsInPool(ctx context.Context, service *v1.Service,
 					errs = append(errs, err)
 				}
 			}
+			// Mark that VM updates happened so the defer will invalidate the vmss cache.
+			// The cache invalidation must happen after all per-node defers complete,
+			// since those defers call DeleteCacheForNode which repopulates the cache.
```
Comment (Liunardy) [inline pkg/provider/azure_vmss.go]: I think the second sentence here should be moved to the defer that invalidates the vmss cache.

File: pkg/provider/azure_vmss.go [hunk 5]
```diff
@@ -2380,6 +2417,7 @@ func (ss *ScaleSet) VMSSBatchSize(ctx context.Context, vmssName string) (int, er
 func (ss *ScaleSet) UpdateVMSSVMsInBatch(ctx context.Context, meta vmssMetaInfo, update map[string]armcompute.VirtualMachineScaleSetVM, batchSize int) <-chan error {
 	logger := klog.FromContext(ctx)
 	patchVMFn := func(ctx context.Context, instanceID string, vm *armcompute.VirtualMachineScaleSetVM) (*runtime.Poller[armcompute.VirtualMachineScaleSetVMsClientUpdateResponse], error) {
+		logger.V(4).Info("UpdateVMSSVMsInBatch: updating vm", "vmss", meta.vmssName, "instanceID", instanceID, "requestEtag", ptr.Deref(vm.Etag, ""))
```
Comment (Liunardy) [inline pkg/provider/azure_vmss.go:2420]: Migrate to contextual logging so there is no need for `UpdateVMSSVMsInBatch:`?

File: pkg/provider/azure_vmss_test.go [hunk 6]
```diff
@@ -3024,6 +3024,11 @@ func TestEnsureHostsInPool(t *testing.T) {
 
 				err = ss.EnsureHostsInPool(context.Background(), &v1.Service{}, test.nodes, test.backendpoolID, test.vmSetName)
 				assert.Equal(t, test.expectedErr, err != nil, test.description+errMsgSuffix)
+
+				if test.expectedVMSSVMPutTimes > 0 && !test.expectedErr {
+					_, exists, _ := ss.vmssCache.GetStore().GetByKey(consts.VMSSKey)
```
Comment (Liunardy) [inline pkg/provider/azure_vmss_test.go]: Can you check it exists before? If it doesn't exist even before calling the function, this check will be useless. Same with the other test.

File: pkg/provider/azure_vmss.go (hunk 4 above)
Comment (Liunardy) [reply pkg/provider/azure_vmss.go]: Same with the other comment in ensureBackendPoolDeleted.

File: pkg/provider/azure_vmss.go (hunk 3 above)
Comment (Liunardy) [reply pkg/provider/azure_vmss.go]: Same with the other log in ensureBackendPoolDeleted.

File: pkg/provider/azure_vmss.go (hunk 2 above)
Comment (Liunardy) [reply pkg/provider/azure_vmss.go:1360]: Same with other logs that delete cache.

Comment (nilo19) [reply pkg/provider/azure_vmss.go:1360]: I'm trying not to touch lines out of scope of this pr.

File: pkg/provider/azure_vmss.go (hunk 5 above)
Comment (nilo19) [reply pkg/provider/azure_vmss.go:2420]: created an issue https://github.com/kubernetes-sigs/cloud-provider-azure/issues/9890

File: pkg/provider/azure_vmss.go (hunk 4 above)
Comment (nilo19) [reply pkg/provider/azure_vmss.go]: done

File: pkg/provider/azure_vmss.go (hunk 3 above)
Comment (nilo19) [reply pkg/provider/azure_vmss.go]: done

File: pkg/provider/azure_vmss.go (hunk 1 above)
Comment (nilo19) [reply pkg/provider/azure_vmss.go]: done

File: pkg/provider/azure_vmss_test.go (hunk 6 above)
Comment (nilo19) [reply pkg/provider/azure_vmss_test.go]: leave the check here, and add a dedicated test for pre-checking cache before calling the function.

Comment (Liunardy) [reply pkg/provider/azure_vmss_test.go]: The check here and in TestEnsureBackendPoolDeleted can be removed since this cache invalidation check is incomplete without the pre-check and there is a dedicated test with pre-check now.

File: pkg/provider/azure_vmss.go [hunk 7]
```diff
@@ -1415,6 +1418,19 @@ func (ss *ScaleSet) ensureHostsInPool(ctx context.Context, service *v1.Service,
...
 
+	// Track if any VM updates happened to invalidate vmss cache after all defers run
+	// The cache invalidation must happen after all per-node defers complete,
+	// since those defers call DeleteCacheForNode which repopulates the cache.
+	hasVMUpdates := false
+	defer func() {
+		if hasVMUpdates {
+			logger.V(2).Info("invalidating vmss cache after updating vms", "reason", "vmss vms updated")
+			if err := ss.vmssCache.Delete(consts.VMSSKey); err != nil {
+				logger.Info("Failed to invalidate vmss cache", "err", err)
```
Comment (Liunardy) [inline pkg/provider/azure_vmss.go:1429]: Just checking is the verbosity level good here for the error message? Same thing with V(2) for the cache invalidation.

Comment (nilo19) [reply pkg/provider/azure_vmss.go:1429]: I think this is an error and should have highest priority with v=0.

File: pkg/provider/azure_vmss_test.go (hunk 6 above)
Comment (nilo19) [reply pkg/provider/azure_vmss_test.go]: deleted.
