### PR TITLE
Fix availability set cache in vmss cache

### LINKED ISSUE #363: If nodes are are not in a ready state when the controller manager boots, the cache is stale causing 15 min delay of LB deployment
**What happened**:
When adding functionality to the e2e tests in https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/857 for CAPZ, I found the e2e tests would fail if run against a single control plane node cluster.  This would occasionally happen when running multi-node control plane clusters as well.  This was initially reported with some of the message in #338

What happens is the control manager comes [online and queries for azure machines power status.](https://github.com/kubernetes/kubernetes/blob/ec560b9737537be8c688776461bc700e8ddedb9d/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss.go#L211)  Since the machines are not available yet [they are not in the cache.](https://github.com/kubernetes/kubernetes/blob/ec560b9737537be8c688776461bc700e8ddedb9d/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss_cache.go#L307) When the request comes in for the [load balancer the cache is queried](https://github.com/kubernetes/kubernetes/blob/ec560b9737537be8c688776461bc700e8ddedb9d/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss.go#L1196) and reports that the node [does not exist as a VMAS and attempts to run the VMSS code](https://github.com/kubernetes/kubernetes/blob/ec560b9737537be8c688776461bc700e8ddedb9d/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss.go#L1217) hence the following error message.  When it is found the in the cache it goes down the [correct code path](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss.go#L1272).

```
E0802 23:30:06.928574       1 azure_vmss.go:1116] EnsureHostInPool(default/ingress-nginx-ilb): backendPoolID(/subscriptions/b9d9436a-0c07-4fe8-b779-2c1030bd7997/resourceGroups/capz-e2e-72fll1/providers/Microsoft.Network/loadBalancers/capz-e2e-72fll1-internal/backendAddressPools/capz-e2e-72fll1) - failed to ensure host in pool: "not a vmss instance"
```

I was able to confirm the cache was missing the node by adding some custom logs to the controller-manager. The initial [request to the cache](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss_cache.go#L277) doesn't have the nodes:

```
I0802 23:27:42.217347       1 azure_vmss.go:309] Can not extract scale set name from providerID (azure:///subscriptions/b9d9436a-0c07-4fe8-b779-2c1030bd7997/resourceGroups/capz-e2e-72fll1/providers/Microsoft.Compute/virtualMachines/capz-e2e-72fll1-control-plane-wjqp5), assuming it is mananaged by availability set: not a vmss instance
I0802 23:27:42.217487       1 azure_vmss.go:192] JJS: powerstatus node capz-e2e-72fll1-control-plane-wjqp5
I0802 23:27:42.217638       1 azure_vmss_cache.go:238] JJS: enter cache calls for nodes
I0802 23:27:42.217725       1 azure_vmss_cache.go:240] JJS: listing nodes for rg: capz-e2e-72fll1
I0802 23:27:42.651485       1 azure_backoff.go:100] VirtualMachinesClient.List(capz-e2e-72fll1) success
I0802 23:27:42.651641       1 azure_vmss_cache.go:246] JJS: nodes found: %!s(int=1)
I0802 23:27:42.651750       1 azure_vmss_cache.go:249] JJS: adding node to local cache {{%!s(*http.Response=<nil>)} %!s(*compute.Plan=<nil>) %!s(*compute.VirtualMachineProperties=&{0xc001fd3eb0 0xc002022960 <nil> 0xc001f13ea0 0xc0020280a0 <nil> <nil> <nil> <nil>   <nil> <nil> 0xc001fd3fd0 <nil> <nil> 0xc001fd3ea0}) %!s(*[]compute.VirtualMachineExtension=<nil>) %!s(*compute.VirtualMachineIdentity=<nil>) %!s(*[]string=&[1]) %!s(*string=0xc001fd2a60) %!s(*string=0xc001fd2a50) %!s(*string=0xc001fd2a70) %!s(*string=0xc001fd2a80) map[Name:%!s(*string=0xc001fd2a90) creationTimestamp:%!s(*string=0xc001fd2ab0) jobName:%!s(*string=0xc001fd2ad0) kubernetes.io_cluster_capz-e2e-72fll1-control-plane-wjqp5:%!s(*string=0xc001fd2af0) sigs.k8s.io_cluster-api-provider-azure_cluster_capz-e2e-72fll1:%!s(*string=0xc001fd2b10) sigs.k8s.io_cluster-api-provider-azure_role:%!s(*string=0xc001fd2b30)]}
I0802 23:27:42.651962       1 azure_vmss_cache.go:278] JJS: VMAS Nodes: map[capz-e2e-72fll1-control-plane-wjqp5:{}]
I0802 23:27:42.652194       1 azure_vmss_cache.go:280] JJS: asking for node capz-e2e-72fll1-control-plane-wjqp5
I0802 23:27:42.698224       1 azure_instances.go:232] InstanceShutdownByProviderID gets power status "running" for node "capz-e2e-72fll1-control-plane-wjqp5"
```

You can see request for powerstatus here:

```
I0802 23:28:32.709471       1 azure_vmss.go:192] JJS: powerstatus node capz-e2e-72fll1-md-0-q2st9
I0802 23:28:32.709626       1 azure_vmss_cache.go:278] JJS: VMAS Nodes: map[capz-e2e-72fll1-control-plane-wjqp5:{}]
I0802 23:28:32.709652       1 azure_vmss_cache.go:280] JJS: asking for node capz-e2e-72fll1-md-0-q2st9
I0802 23:28:32.709836       1 azure_vmss.go:309] Can not extract scale set name from providerID (azure:///subscriptions/b9d9436a-0c07-4fe8-b779-2c1030bd7997/resourceGroups/capz-e2e-72fll1/providers/Microsoft.Compute/virtualMachines/capz-e2e-72fll1-md-0-q2st9), assuming it is mananaged by availability set: not a vmss instance
```

And request for [EnsureHostsInPool](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss.go#L1178) doesn't have the VMAS nodes in the cache:

```
I0802 23:30:06.928474       1 azure_vmss.go:1077] JJS: EnsureHostsInPool node capz-e2e-72fll1-md-0-q2st9
I0802 23:30:06.928488       1 azure_vmss_cache.go:278] JJS: VMAS Nodes: map[capz-e2e-72fll1-control-plane-wjqp5:{}]
I0802 23:30:06.928518       1 azure_vmss_cache.go:280] JJS: asking for node capz-e2e-72fll1-md-0-q2st9
I0802 23:30:06.928529       1 azure_vmss.go:1097] JJS: EnsureHostsInPool node false managedby VMAS
I0802 23:30:06.928542       1 azure_vmss.go:1113] JJS: EnsureHostsInPool entered EnsureHostInPool started%!(EXTRA bool=false)
I0802 23:30:06.928549       1 azure_vmss.go:832] ensuring node "capz-e2e-72fll1-md-0-q2st9" of scaleset "" in LB backendpool "/subscriptions/b9d9436a-0c07-4fe8-b779-2c1030bd7997/resourceGroups/capz-e2e-72fll1/providers/Microsoft.Network/loadBalancers/capz-e2e-72fll1-internal/backendAddressPools/capz-e2e-72fll1"
E0802 23:30:06.928574       1 azure_vmss.go:1116] EnsureHostInPool(default/ingress-nginx-ilb): backendPoolID(/subscriptions/b9d9436a-0c07-4fe8-b779-2c1030bd7997/resourceGroups/capz-e2e-72fll1/providers/Microsoft.Network/loadBalancers/capz-e2e-72fll1-internal/backendAddressPools/capz-e2e-72fll1) - failed to ensure host in pool: "not a vmss instance"
```

**What you expected to happen**:

**How to reproduce it**:
Follow the instructions at https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/857  or create a single node control plane cluster then after the control node is up, add a worker node.

**Anything else we need to know?**:
In multi control plane node clusters, leader election occurs in the controller-manager and causes the cache to reload.  This is why it only happens occasionally in that scenario.  

I believe this could happen if a node is added at a later time and was expected to be in the backend pool but wasn't and so could be important to fix.

**Environment**:
- Kubernetes version (use `kubectl version`): `1.18.6`
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: CAPZ
- Others:

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

 /kind bug

**What this PR does / why we need it**:  This fixes a bug affecting clusters with virtual machines when vmType is set to "vmss". What happens is the control manager comes online and queries for azure machines power status. Since the machines are not available yet they are not in the cache. When the request comes in for the load balancer the cache is queried and reports that the node does not exist as a VMAS and attempts to run the VMSS code hence the following error message: `failed: not a vmss instance`. The same error also occurs when trying to expose a load balancer service. When it is found the cache it goes down the correct code path.

This adds logic to the vmss cache to refresh the availability set cache if the node it is querying for has joined the cluster since the last cache refresh, or if the cache has expired. Note that this approach minimizes cache refreshes by not refreshing unless necessary, but it does add extra GET API calls whenever a new node joins the cluster. This can be skipped altogether with the `DisableAvailabilitySetNodes` flag that is already implemented. It's not perfect but it will fix most scenarios for CAPZ. In the future, I'd like to propose a new "mixed" or "hybrid" VMSet implementation that is truly aware of both VMs and VMSS nodes as a more long term fix.

**Which issue(s) this PR fixes**:

Fixes #363 

**Special notes for your reviewer**: @feiskyer if I want this fix to make it back into the in tree provider, what's the best way to proceed?

**Release note**:
```
Fix availability set cache in vmss cache
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
will fix/add UTs shortly. Please feel free to review the code in the meantime.

File: pkg/provider/azure_vmss_cache.go [hunk 1]
```diff
@@ -286,11 +291,22 @@ func (ss *scaleSet) newAvailabilitySetNodesCache() (*azcache.TimedCache, error)
...
 
+		// store all the node names in the cluster when the cache data was created.
+		nodeNames, err := ss.GetNodeNames()
+		if err != nil {
+			return nil, err
+		}
+
+		localCache := availabilitySetEntry{
+			vmNames:   vmNames,
+			nodeNames: nodeNames,
```
Comment (feiskyer) [inline pkg/provider/azure_vmss_cache.go:307]: this doesn't look right. The nodeNames here include all nodes, including VMAS and VMSS

File: pkg/provider/azure_vmss.go [hunk 2]
```diff
@@ -210,7 +211,7 @@ func (ss *scaleSet) getVmssVM(nodeName string, crt azcache.AzureCacheReadType) (
 
 // GetPowerStatusByNodeName returns the power state of the specified node.
 func (ss *scaleSet) GetPowerStatusByNodeName(name string) (powerState string, err error) {
-	managedByAS, err := ss.isNodeManagedByAvailabilitySet(name, azcache.CacheReadTypeUnsafe)
```
Comment (feiskyer) [inline pkg/provider/azure_vmss.go:213]: This change would cause every not found node to trigger cache updates and may cause issues when a large number of nodes are deleted or newly created. Have you done some validations on these scenarios?

File: pkg/provider/azure_vmss_cache.go [hunk 3]
```diff
@@ -57,6 +57,11 @@ type vmssEntry struct {
 	lastUpdate    time.Time
 }
 
+type availabilitySetEntry struct {
```
Comment (feiskyer) [inline pkg/provider/azure_vmss_cache.go:60]: And the cache type changes above is required, then I don't think this entry is needed since the cache has already been force refreshed.

File: pkg/provider/azure_vmss_cache.go (hunk 1 above)
Comment (CecileRobertMichon) [reply pkg/provider/azure_vmss_cache.go:307]: It actually includes all nodes intentionally. The idea is that we only want to fetch the VM list if we absolutely have to in order to know if it's vmas or vmss. If the node is new to the cluster, there is a chance it wasn't added in the cache last time we fetched the VM list, so we have to fetch the list again. If it was already in the cluster last time we checked the cache, we don't need to check again, because if it was VM it would be in the cache. If it's a cache miss we don't need to check again, it's safe to assume it's VMSS.

File: pkg/provider/azure_vmss.go (hunk 2 above)
Comment (CecileRobertMichon) [reply pkg/provider/azure_vmss.go:213]: Correct. See my note in PR description: 
> Note that this approach minimizes cache refreshes by not refreshing unless necessary, but it does add extra GET API calls whenever a new node joins the cluster. This can be skipped altogether with the DisableAvailabilitySetNodes flag that is already implemented. It's not perfect but it will fix most scenarios for CAPZ. In the future, I'd like to propose a new "mixed" or "hybrid" VMSet implementation that is truly aware of both VMs and VMSS nodes as a more long-term fix.

We already do the same thing for VMSS: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_vmss.go#L182-L188

There isn't a way to avoid this, unfortunately, if the node just joined the cluster and we've never fetched its corresponding VM/VMSS.

File: pkg/provider/azure_vmss_cache.go (hunk 3 above)
Comment (CecileRobertMichon) [reply pkg/provider/azure_vmss_cache.go:60]: See my comment above. This is needed in order to store the state of nodeNames at the time the cache entry was created in order to determine if it's worth doing a refresh of the cache. We're not doing a force refresh unless 1) the VM is not found, and 2) the node is new to the cluster

File: pkg/provider/azure_vmss.go (hunk 2 above)
Comment (jsturtevant) [reply pkg/provider/azure_vmss.go:213]: since we are doing the refresh below based on the new diff between new nodes and known vms, I am not sure that this change is required?  If it isn't in the cache but the node is new then it is forced by https://github.com/kubernetes-sigs/cloud-provider-azure/pull/537/files#diff-e6715e02b5aa5f8b693bf3e14dd99dd9a160f0f0f1481df96891af24fc3a5fffR333

Comment (jsturtevant) [reply pkg/provider/azure_vmss.go:213]: > may cause issues when a large number of nodes are deleted or newly created

This will only be an issue if the nodes come up in sequence? I.E. if a node is added every 5 mins we would have an api call every five minutes.  

Do we have any data on how often that type scenario occurs?  Maybe during node auto scaler operations?

**Comment by jsturtevant** [comment]
I think this does solve the 15 mins on initial boot or when the nodes are fetch right before a scale event and it does mitigate the extra api calls by only doing it if the node is new to the cluster.

Couple of thoughts for the future:

- Do we have any types of tests or data that calculates the number of API calls to see if a code change make a significant increase in the number of api calls?
- Is there an label on the node that allows for us to determine if it is VMSS or VMAS? Is that something worth considering?

File: pkg/provider/azure.go [hunk 4]
```diff
@@ -927,6 +936,22 @@ func (az *Cloud) GetNodeResourceGroup(nodeName string) (string, error) {
 	return az.ResourceGroup, nil
 }
 
+// GetNodes returns a set of all node names in the k8s cluster.
```
Comment (aramase) [inline pkg/provider/azure.go:939]: nit: s/GetNodes/GetNodeNames

File: pkg/provider/azure_vmss.go (hunk 2 above)
Comment (aramase) [reply pkg/provider/azure_vmss.go:213]: Yeah, I think we can keep the cache read type unsafe as we are doing a force refresh if not found in the cache.

**Comment by aramase** [comment]
> Is there an label on the node that allows for us to determine if it is VMSS or VMAS? Is that something worth considering?

Typically this is determined from the `ProviderID` field on the node? But if the node has not yet been registered, then the field is empty.

File: pkg/provider/azure_vmss.go (hunk 2 above)
Comment (CecileRobertMichon) [reply pkg/provider/azure_vmss.go]: > Yeah, I think we can keep the cache read type unsafe as we are doing a force refresh if not found in the cache.

Correct, reverted that change

**Review by feiskyer — COMMENTED** [review]
/hold cancel

/lgtm
/approve

File: pkg/provider/azure_vmss.go (hunk 2 above)
Comment (feiskyer) [reply pkg/provider/azure_vmss.go]: thanks for the discussion and addressing the issues
