### PR TITLE
Fix : Enable system tag support prefix match

### LINKED ISSUE #8053: SystemTags should support comparing with substring, not just full string
#### What would you like to be added:

We compare if a tag key is system reserved by strings.EqualFold. If the number of system reserved tag keys are huge, SystemTags will be long. For enhancement, we should support comparison with full string and substring at a time, to reduce the length of SystemTags.

#### Why is this needed:

To reduce the length of SystemTags.

### PR DESCRIPTION
**Pull request by Timberlake-Z**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

In the logic for updating tags, if we define `systemTags`, any tags not included in `systemTags` will be deleted. However, this behavior can cause some AKS-managed tags to be mistakenly deleted. Adding all AKS-managed tags individually to `systemTags` would make `systemTags` excessively long and difficult to maintain.

This PR enhances the comparison logic between tags and `systemTags` by introducing prefix matching. With this change, we can add a prefix like `aks-managed` to `systemTags`, and any tags starting with `aks-managed`, such as `aks-managed-cluster-name` or `aks-managed-cluster-rg`, will be successfully matched and retained, preventing accidental deletion.

This approach reduces the size of `systemTags` while maintaining flexibility and ensuring that AKS-managed tags are preserved.

#### Which issue(s) this PR fixes:

Fixes #8053 

#### Does this PR introduce a user-facing change?

```release-note
- Introduced **prefix-based matching** for `systemTags` during tag reconciliation.
- Tags starting with a prefix defined in `systemTags` (e.g., `aks-managed`) will now be matched and retained.
- For example:  Adding `aks-managed` to `systemTags` ensures tags like `aks-managed-cluster-name` and `aks-managed-cluster-rg` are preserved.

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/provider/azure_utils.go [hunk 1]
```diff
@@ -109,6 +110,25 @@ func findKeyInMapCaseInsensitive(targetMap map[string]*string, key string) (bool
...
 
+// This function extends the functionality of findKeyInMapCaseInsensitive by supporting both
+// exact case-insensitive key matching and prefix-based key matching in the given map.
+// 1. If the key is found in the map (case-insensitively), the function returns true and the matching key in the map.
+// 2. If the key's prefix is found in the map (case-insensitively), the function also returns true and the matching key in the map.
+// This function is designed to enable systemTags to support prefix-based tag keys,
+// allowing more flexible and efficient tag key matching.
+func findKeyInMapWithPrefix(targetMap map[string]*string, key string) (bool, string) {
+	for k := range targetMap {
+		if strings.EqualFold(k, key) {
```
Comment (nilo19) [inline pkg/provider/azure_utils.go:121]: I don't think we need this.

File: pkg/provider/azure_utils.go [hunk 2]
```diff
@@ -109,6 +110,25 @@ func findKeyInMapCaseInsensitive(targetMap map[string]*string, key string) (bool
 	return false, ""
 }
 
+// This function extends the functionality of findKeyInMapCaseInsensitive by supporting both
```
Comment (nilo19) [inline pkg/provider/azure_utils.go:113]: Where is findKeyInMapCaseInsensitive?

File: pkg/provider/azure_utils_test.go [hunk 3]
```diff
@@ -115,6 +115,69 @@ func TestReconcileTags(t *testing.T) {
...
+			},
+			systemTags: "prefix, sys",
+			expectedTags: map[string]*string{
+				"prefix-a": ptr.To("b"),
+				"sys-b":    ptr.To("c"),
+			},
+			expectedChanged: false,
+		},
+		{
+			description: "reconcileTags should work with PR 11567285",
```
[the remark this answers is not in the document]
Comment (Timberlake-Z) [reply pkg/provider/azure_utils_test.go]: changed
