### PR TITLE
Fix: health probe config should be port-specific

### LINKED ISSUE #949: Health probe configuration should be applied to specific port.
#### What happened:

Health probe configurations are applied to all ports of the service. 

#### What you expected to happen:

Health probe configuration should be applied to specific port.

#### How to reproduce it (as minimally and precisely as possible):

```yaml
apiVersion: v1
kind: Service
metadata:
  name: sctpservice
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol: "tcp"
spec:
  type: LoadBalancer
  selector:
    app: sctpserver
  ports:
    - name: sctpserver
      protocol: SCTP
      port: 30102
      targetPort: 30102
    - name: webserver
      protocol: TCP
      port: 80
      targetPort: 30102
```

#### Anything else we need to know?:

Nothing else

#### Environment:
 Not needed.

### PR DESCRIPTION
**Pull request by MartinForReal**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Health probe configuration should be per-port specific. 
Tcpreset feature is deleted. And test cases should changed accordingly.
set idletimeoutinminutes to 4

#### Which issue(s) this PR fixes:

Fixes #949 

#### Special notes for your reviewer:

when traffic policy is local, lbrule will follow the following pattern instead: svcprefix-tcp-HealthCheckNodePort
Test cases of Tcpreset feature has been removed
A function is added to convert deprecated annotation to new annotations and alter the service object accordingly. 
Generate testsuit.go for e2e test cases

#### Does this PR introduce a user-facing change?
User should adopt new annotation and spec field to configure health probe of load balancer.

```release-note

Following  configuration will be applied to the all ports of service.

"service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol"
"service.beta.kubernetes.io/azure-load-balancer-health-probe-interval"
"service.beta.kubernetes.io/azure-load-balancer-health-probe-num-of-probe"
"service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path"

If health probe is needed, user should specify AppProtocol in port object of Service spec.
And following protocols are supported: http, tcp, https

Additional annotations are added. where port is the port number of port object

service.beta.kubernetes.io/port_{port}_health-probe_interval
service.beta.kubernetes.io/port_{port}_health-probe_num-of-probe
service.beta.kubernetes.io/port_{port}_health-probe_request-path

Please refer to docs.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/provider/azure_loadbalancer.go [hunk 1]
```diff
@@ -2033,161 +1956,247 @@ func lbRuleConflictsWithPort(rule network.LoadBalancingRule, frontendIPConfigID
...
+	}
+
+	// get number of probes
+	numberOfProbes, err := consts.GetInt32HealthProbeConfigOfPortFromK8sSvcAnnotation(annotations, port.Port, consts.HealthProbeParamsNumOfProbe, func(val *int32) error {
+		//minimum number of unhealthy responses is 2. ref: https://docs.microsoft.com/en-us/rest/api/load-balancer/load-balancers/create-or-update#probe
+		const (
+			MinimumNumOfProbe = 2
+		)
+		if *val < MinimumNumOfProbe {
+			return fmt.Errorf("the minimum value of %s is %d", consts.HealthProbeParamsNumOfProbe, MinimumNumOfProbe)
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go:2005]: Can we print the full name of the annotation here? I think that would be more straightforward to the end-users.

File: pkg/provider/azure_loadbalancer.go [hunk 2]
```diff
@@ -2033,161 +1956,247 @@ func lbRuleConflictsWithPort(rule network.LoadBalancingRule, frontendIPConfigID
...
-			path = v
+
+	// get probe interval in seconds
+	probeInterval, err := consts.GetInt32HealthProbeConfigOfPortFromK8sSvcAnnotation(annotations, port.Port, consts.HealthProbeParamsProbeInterval, func(val *int32) error {
+		//minimum probe interval in seconds is 5. ref: https://docs.microsoft.com/en-us/rest/api/load-balancer/load-balancers/create-or-update#probe
+		const (
+			MinimumProbeIntervalInSecond = 5
+		)
+		if *val < 5 {
+			return fmt.Errorf("the minimum value of %s is %d", consts.HealthProbeParamsProbeInterval, MinimumProbeIntervalInSecond)
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go:2025]: same here

**Comment by nilo19** [comment]
Can you add e2e tests for the port-dedicated health probe annotations?

File: pkg/provider/azure_loadbalancer.go (hunk 1 above)
Comment (MartinForReal) [reply pkg/provider/azure_loadbalancer.go:2005]: the full name of the annotation will be added in context.

File: pkg/provider/azure_loadbalancer.go (hunk 2 above)
Comment (MartinForReal) [reply pkg/provider/azure_loadbalancer.go:2025]: the full name of the annotation  will be added in context.

**Comment by MartinForReal** [comment]
@nilo19 @feiskyer any suggestion on how to split this pr is appreciated. Thanks!

**Comment by MartinForReal** [comment]
> probe

test cases for health probe annotations were added.

File: pkg/provider/azure_loadbalancer.go [hunk 3]
```diff
@@ -1933,161 +1857,292 @@ func lbRuleConflictsWithPort(rule network.LoadBalancingRule, frontendIPConfigID
...
+			probe = nodeEndpointHealthprobe
+		} else {
+			err := processDeprecatedHealthProbeAnnotations(service)
+			if err != nil {
+				return expectedProbes, expectedRules, err
+			}
+			for _, port := range service.Spec.Ports {
+				probeProps, err := az.buildHealthProbeRulesForPort(service.Annotations, port)
+				if err != nil {
+					klog.V(2).ErrorS(err, "error occurred when buildHealthProbeRulesForPort", "service", service.Name, "namespace", service.Namespace,
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go:2061]: Why not return the error here?

File: pkg/provider/azure_loadbalancer.go [hunk 4]
```diff
@@ -1933,161 +1857,292 @@ func lbRuleConflictsWithPort(rule network.LoadBalancingRule, frontendIPConfigID
...
-		return protocol, path
+// buildHealthProbeRulesForPort
+// for following sku: basic loadbalancer vs standard load balancer
+// for following protocols: TCP HTTP HTTPS(SLB only)
+func (az *Cloud) buildHealthProbeRulesForPort(annotations map[string]string, port v1.ServicePort) (*network.ProbePropertiesFormat, error) {
+	properties := &network.ProbePropertiesFormat{}
+	// get request path ,only used with http/https probe
+	path, err := consts.GetHealthProbeConfigOfPortFromK8sSvcAnnotation(annotations, port.Port, consts.HealthProbeParamsRequestPath)
+	if err != nil {
+		return nil, errwrap.Wrap(fmt.Errorf("failed to parse annotation %s", consts.BuildHealthProbeAnnotationKeyForPort(port.Port, consts.HealthProbeParamsRequestPath)), err)
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer.go:1868]: What is the benefit of using errwrap compared to %w?

Comment (MartinForReal) [reply pkg/provider/azure_loadbalancer.go:1868]: %w is better.

File: pkg/provider/azure_loadbalancer.go (hunk 3 above)
Comment (MartinForReal) [reply pkg/provider/azure_loadbalancer.go:2061]: will return the error instead

File: pkg/provider/azure_loadbalancer.go [hunk 5]
```diff
@@ -1933,161 +1857,292 @@ func lbRuleConflictsWithPort(rule network.LoadBalancingRule, frontendIPConfigID
...
+			}
 
-		probeProtocol, requestPath := parseHealthProbeProtocolAndPath(service)
-		probeInterval, numberOfProbe, err := getProbeIntervalInSecondsAndNumOfProbe(service)
+		}
+		expectedRules = append(expectedRules, network.LoadBalancingRule{
+			Name:                              &lbRuleName,
+			LoadBalancingRulePropertiesFormat: props,
+		})
+	} else {
```
[the remark this answers is not in the document]
Comment (MartinForReal) [reply pkg/provider/azure_loadbalancer.go:2083]: more comments will be added.

**Comment by MartinForReal** [comment]
> @MartinForReal Shangxiang Fan FTE can you add some e2e tests against these new annotations in `tests/e2e/network/service_annotations.go`? You can refer to https://kubernetes-sigs.github.io/cloud-provider-azure/development/e2e/e2e-tests-azure/ for how to run the e2e tests locally.

I will raise a separate pr for e2e test cases

**Comment by feiskyer** [comment]
@MartinForReal could you check why those e2e tests are failing?

**Comment by MartinForReal** [comment]
I'm on it.

**Comment by nilo19** [comment]
/hold
Please enrich the e2e test for this one.
