### PR TITLE
[release 1.1] Add detailed error reuslt_code in ObserveOperationWithR…

### LINKED ISSUE #1986: Analyze detailed error code and add to latency logs
When errors happen, the current result_code is always "failed". We need to pass in the error, extract the error code and then log into latency logs.​

Please ensure there is no space or special chars included in the "result_code" as the latency logs would be analyzed later by expr operations.

Refer https://github.com/kubernetes-sigs/cloud-provider-azure/blob/a639e364d7903a260acb61a294426027ee710a9a/pkg/metrics/azure_metrics.go#L95-L105

### PR DESCRIPTION
**Pull request by monianshouhou**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
When errors happen, the current result_code is always "failed" in ObserveOperationWithResult func.
Now the result_code turns to something like "failed_create_route",  "failed_ensure_loadbalancer" and so on.
#### Which issue(s) this PR fixes:

Fixes #1986 

#### Does this PR introduce a user-facing change?

```release-note
Result_code in latency logs is more detailed.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/metrics/azure_metrics.go [hunk 1]
```diff
@@ -99,6 +99,9 @@ func (mc *MetricContext) ObserveOperationWithResult(isOperationSucceeded bool, l
 	resultCode := "succeeded"
 	if !isOperationSucceeded {
 		resultCode = "failed"
+		if len(mc.attributes) > 0 {
```
Comment (monianshouhou) [inline pkg/metrics/azure_metrics.go:102]: UT test needs 1.2.0 logr, so UT test is temporarily removed and will be added in the future.
