### PR TITLE
fix: Remove all routes that have the node name as prefix

### LINKED ISSUE #8175: Remove outdated routes after node's podcidr changes
#### What happened:

The suffix of a route name is [generated from podcidr of the node](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/v1.29.11/pkg/provider/azure_routes.go#L514). In some cases after the node being deleted and re-created podcidr changes, and the generated route name to be deleted will not be included in existing routes. So the outdated route with a different name [will not be deleted](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/v1.29.11/pkg/provider/azure_routes.go#L170).

#### What you expected to happen:

Those outdated routes should be removed.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by nilo19**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

When a delete route operation comes in, not only the route with exactly the name should be deleted, but also all routes that have the node name as prefix should be deleted.

#### Which issue(s) this PR fixes:

Fixes #8175

#### Special notes for your reviewer:

To reduce the potential impact, I separate the two deletion logic by adding a new for loop, instead of integrating them into one loop.

#### Does this PR introduce a user-facing change?

```release-note
fix: Remove all routes that have the node name as prefix
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/provider/azure_routes.go [hunk 1]
```diff
@@ -179,6 +180,18 @@ func (d *delayedRouteUpdater) updateRoutes(ctx context.Context) {
 				break
 			}
 		}
+		// After removing the matched routes (if any), loop again to remove the outdated routes,
+		// whose name and IP addresses may not match but target the same node.
+		for i, existingRoute := range routes {
```
Comment (nilo19) [inline pkg/provider/azure_routes.go:185]: To reduce the potential impact, I separate the two deletion logic by adding a new for loop, instead of integrating them into one loop.

**Review by feiskyer — COMMENTED** [review]
LGTM, thanks for the fix

/lgtm
/retest
