### PR TITLE
fix: remove auto approval restriction

### LINKED ISSUE #1859: AKS Private Link Service requires global visbility
#### What happened:
Creating a private link service as [follows](https://github.com/kubernetes-sigs/cloud-provider-azure/issues/872):
```
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: my-namespace
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-pls-create: "true"
    # Does not work without: service.beta.kubernetes.io/azure-pls-visibility: "*"
    # service.beta.kubernetes.io/azure-pls-visibility: "<UUID>" does not work either
    service.beta.kubernetes.io/azure-pls-auto-approval: "<UUID>"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-app
```

The auto approval does not apply without pls-visibility set to *. The following controller event is surfaced: `reconcilePLSVisibility: autoApproval only takes effect when visibility is set to "*"`

#### What you expected to happen:
I should be able to specify visibility and approval to the same subscription, removing the need for global visibility. This capability is present in the console: 
Screen Shot 2022-06-16 at 1 30 30 PM

```
service.beta.kubernetes.io/azure-pls-visibility: *
service.beta.kubernetes.io/azure-pls-auto-approval: "<UUID>"
``` 
is the third option and not ideal.

#### How to reproduce it (as minimally and precisely as possible):
Apply service definition above.

#### Anything else we need to know?:
N/A

#### Environment:
AKS

- Kubernetes version (use `kubectl version`): AKS 1.22.4
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others:

### PR DESCRIPTION
**Pull request by jwtty**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Remove redundant restriction on pls autoApproval and visibility.
User can specify a list of subscriptions for visibility and a subset of this list for autoApproval.

#### Which issue(s) this PR fixes:

Fixes #1859 

#### Does this PR introduce a user-facing change?

```release-note
Remove redundant restriction on pls autoApproval and visibility.
User can specify a list of subscriptions for visibility (e.g. "sub1 sub2") and a subset of this list for autoApproval (e.g. "sub1").
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/provider/azure_privatelinkservice.go [hunk 1]
```diff
@@ -451,11 +451,8 @@ func reconcilePLSVisibility(
 	service *v1.Service,
 ) (bool, error) {
 	changed := false
-	visibilitySubs, anyoneCanView := getPLSVisibility(service)
+	visibilitySubs, _ := getPLSVisibility(service)
```
Comment (lzhecheng) [inline pkg/provider/azure_privatelinkservice.go:454]: Since it is the only place to call `getPLSVisibility(), why not just return `visibilityList`?

Comment (jwtty) [reply pkg/provider/azure_privatelinkservice.go:454]: I want to keep it in case it's needed in the future.
