### PR TITLE
Multi-slb related bug fixes

### LINKED ISSUE #6980: Empty ip address should be ignored when updating an ip-based backend pool
#### What happened:

We should ignore the illegal backend pool requests with empty ip addresses.

#### What you expected to happen:

Empty ip address should not be added to the backend pool.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### LINKED ISSUE #7113: In multi-slb mode, local service endpoints could be ignored
#### What happened:

In multi-slb mode, we only watch the one endpointslice for each local service. However, the service could have more than one endpointslices.

#### What you expected to happen:

All endpointslices should be respected.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### LINKED ISSUE #7200: Unable to create k8s service of type loadbalancer using internal load balancer
After upgrading from Azure Cloud Controller Manager (CCM) version v1.27.17 to version v1.29.9, we are unable to create a new
service of type 'Loadbalancer' using the internal load balancer 'kubernetes-internal'.

Please note that this is a self-managed k8s cluster, not one managed by AKS.

If the matter is security related, please disclose it privately via https://kubernetes.io/security/
-->

#### What happened:
We tried to create a service of type loadbalancer after upgrading the Azure CCM from version 1.27.17 to version v1.29.9. The service never transitioned past the pending state. Existing services of type loadbalancer using the internal load balancer remained operational.

#### What you expected to happen:
Create a service of type loadbalancer using an internal load balancer.

#### How to reproduce it (as minimally and precisely as possible):
Create a new service of type loadbalancer configured to use an internal load balancer.

#### Environment:

- Kubernetes version (use `kubectl version`): v1.29.4
- Cloud provider or hardware configuration: A self-managed k8s cluster. We are not using AKS.
- OS (e.g: `cat /etc/os-release`): Ubuntu 22.04.4 LTS
- Kernel (e.g. `uname -a`): 6.5.0-1025-azure #26~22.04.1-Ubuntu SMP Thu Jul 11 22:33:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug): cilium v1.14.13

- Others:
[k8s_upgrade_azure_ccm_bug_internal-lb.txt](https://github.com/user-attachments/files/17259208/k8s_upgrade_azure_ccm_bug_internal-lb.txt)

### PR DESCRIPTION
**Pull request by nilo19**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

1. All endpointslices of a local service should be included in local backend pool updater, instead of only the first endpointslice.
2. In some rare cases, migration from NIC to IP-based LB can be in a middle state where the NIC references are removed, but those IPConfigs in the backend pool are not. In this case, we should manually exclude those IPConfigs from the request body.
3. localServiceOwnsBackendPool should compare the full backend pool name, not just prefix, because two service names can share the same prefix.
4. There is a corner case when the cluster is being updated to multi-slb from classic NIC-based single lb, not from an IP-based cluster. In this case, if the service being reconciled is local, the cloud provider will try to update a NIC pool to IP-based pool direct, which is not allowed. We should skip adding IPs to NIC-based pool in multi-slb mode.
5. There is a bug in ReconcileBackendPools, where we by mistake parse the LB name to use as the backend pool name.

#### Which issue(s) this PR fixes:

Fixes #7113
Fixes #7200
Fixes #6980 

#### Does this PR introduce a user-facing change?

```release-note
Fix: several bugs related to multiple standard load balancers mode.
1. All endpointslices of a local service should be included in local backend pool updater, instead of only the first endpointslice.
2. In some rare cases, migration from NIC to IP-based LB can be in a middle state where the NIC references are removed, but those IPConfigs in the backend pool are not. In this case, we should manually exclude those IPConfigs from the request body.
3. localServiceOwnsBackendPool should compare the full backend pool name, not just prefix, because two service names can share the same prefix.
4. There is a corner case when the cluster is being updated to multi-slb from classic NIC-based single lb, not from an IP-based cluster. In this case, if the service being reconciled is local, the cloud provider will try to update a NIC pool to IP-based pool direct, which is not allowed. We should skip adding IPs to NIC-based pool in multi-slb mode.
5. There is a bug in ReconcileBackendPools, where we by mistake parse the LB name to use as the backend pool name.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/provider/azure_loadbalancer_backendpool.go [hunk 1]
```diff
@@ -425,10 +424,12 @@ func (bi *backendPoolTypeNodeIP) EnsureHostsInPool(ctx context.Context, service
...
 				return nil
 			}
-			activeNodes, err = bi.getLocalServiceEndpointsNodeNames(ctx, service)
-			if err != nil {
-				return err
-			}
+			activeNodes = bi.getLocalServiceEndpointsNodeNames(service)
+		}
+
+		if isNICPool(backendPool) {
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer_backendpool.go:430]: fix no. 4

File: pkg/provider/azure_loadbalancer_backendpool.go [hunk 2]
```diff
@@ -886,7 +889,13 @@ func removeNodeIPAddressesFromBackendPool(
 		if addresses[i].LoadBalancerBackendAddressPropertiesFormat != nil {
 			ipAddress := ptr.Deref((*backendPool.LoadBalancerBackendAddresses)[i].IPAddress, "")
 			if ipAddress == "" {
-				klog.V(4).Infof("removeNodeIPAddressFromBackendPool: LoadBalancerBackendAddress %s is not IP-based, skipping", ptr.Deref(addresses[i].Name, ""))
+				if isNodeIP {
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer_backendpool.go:892]: fix no. 2

File: pkg/provider/azure_loadbalancer_backendpool.go [hunk 3]
```diff
@@ -633,7 +634,7 @@ func (bi *backendPoolTypeNodeIP) ReconcileBackendPools(ctx context.Context, clus
 		if isMigration && bi.EnableMigrateToIPBasedBackendPoolAPI {
 			var backendPoolNames []string
 			for _, id := range lbBackendPoolIDsSlice {
-				name, err := getLBNameFromBackendPoolID(id)
+				name, err := getBackendPoolNameFromBackendPoolID(id)
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer_backendpool.go:637]: fix no. 6

File: pkg/provider/azure_local_services.go [hunk 4]
```diff
@@ -446,8 +445,10 @@ func (az *Cloud) getLocalServiceBackendPoolID(serviceName string, lbName string,
 
 // localServiceOwnsBackendPool checks if a backend pool is owned by a local service.
 func localServiceOwnsBackendPool(serviceName, bpName string) bool {
-	prefix := strings.Replace(serviceName, "/", "-", -1)
-	return strings.HasPrefix(strings.ToLower(bpName), strings.ToLower(prefix))
+	if strings.HasSuffix(strings.ToLower(bpName), consts.IPVersionIPv6StringLower) {
```
Comment (nilo19) [inline pkg/provider/azure_local_services.go:448]: fix no. 3

File: pkg/provider/azure_local_services.go [hunk 5]
```diff
@@ -463,50 +464,30 @@ func newServiceInfo(ipFamily, lbName string) *serviceInfo {
...
+func (az *Cloud) getLocalServiceEndpointsNodeNames(service *v1.Service) *utilsets.IgnoreCaseSet {
+	var eps []*discovery_v1.EndpointSlice
 	az.endpointSlicesCache.Range(func(_, value interface{}) bool {
 		endpointSlice := value.(*discovery_v1.EndpointSlice)
 		if strings.EqualFold(getServiceNameOfEndpointSlice(endpointSlice), service.Name) &&
 			strings.EqualFold(endpointSlice.Namespace, service.Namespace) {
-			ep = endpointSlice
-			foundInCache = true
-			return false
+			eps = append(eps, endpointSlice)
```
Comment (nilo19) [inline pkg/provider/azure_local_services.go:473]: fix no. 1

File: pkg/provider/azure_local_services_test.go [hunk 6]
```diff
@@ -546,27 +545,26 @@ func TestCheckAndApplyLocalServiceBackendPoolUpdates(t *testing.T) {
...
-			if tc.existingEPS != nil {
-				client = fake.NewSimpleClientset(&svc, tc.existingEPS)
-			} else {
-				client = fake.NewSimpleClientset(&svc)
-			}
+			// var client kubernetes.Interface
+			client := fake.NewSimpleClientset(&svc)
+			// if tc.existingEPS != nil {
+			// 	client = fake.NewSimpleClientset(&svc, tc.existingEPS)
+			// } else {
```
Comment (feiskyer) [inline pkg/provider/azure_local_services_test.go:565]: nit: delete unused codes

File: pkg/provider/azure_loadbalancer_repo.go [hunk 7]
```diff
@@ -380,3 +379,18 @@ func (az *Cloud) serviceOwnsRule(service *v1.Service, rule string) bool {
...
 	return strings.HasPrefix(strings.ToUpper(rule), strings.ToUpper(prefix))
 }
+
+func isNICPool(bp network.BackendAddressPool) bool {
+	logger := klog.Background().WithName("isNICPool").WithValues("backendPoolName", ptr.Deref(bp.Name, ""))
+	if bp.BackendAddressPoolPropertiesFormat != nil &&
+		bp.LoadBalancerBackendAddresses != nil {
+		for _, addr := range *bp.LoadBalancerBackendAddresses {
+			if ptr.Deref(addr.IPAddress, "") == "" {
+				logger.Info("The load balancer backend address has empty ip address, assuming it is a NIC pool",
```
Comment (feiskyer) [inline pkg/provider/azure_loadbalancer_repo.go:389]: change to v(4)

File: pkg/provider/azure_local_services_test.go (hunk 6 above)
Comment (nilo19) [reply pkg/provider/azure_local_services_test.go]: removed

File: pkg/provider/azure_loadbalancer_repo.go (hunk 7 above)
Comment (nilo19) [reply pkg/provider/azure_loadbalancer_repo.go]: changed

**Comment by feiskyer** [comment]
Thanks for the fixes 
/lgtm
