### PR TITLE
fix: Ensure vnet ID will be attached to backend pool in local service…

### LINKED ISSUE #6172: Issues with LB Creation
#### What happened:
Prior to 1.28.X LB creation would succeed as expected. After upgrading cluster to 1.28.5 and subsequently 1.29.4, all LB service creates fail to properly add backend pools to the LB because they are missing VNet/Subnet properties.

#### What you expected to happen:'

Expectation is that the payload from creating LB resources in K8s would contain all properties needed for ANP

#### How to reproduce it (as minimally and precisely as possible):
On 1.29.4 while using backendpool configuration of NodeIP and multiple standard load balancers; attempt to create a lb service in K8s - the LB backend pool is created with empty values, and the LB is not properly updated because it is missing VNet/Subnet properites.

#### Environment:

- Kubernetes version (use `kubectl version`): 1.29.4
- Cloud provider or hardware configuration:
- {

  "cloud": "AzurePublicCloud",
  "tenantId": "XXXXXX",
  "subscriptionId": "XXXXXX",
  "aadClientId": "XXXXXX",
  "aadClientSecret": "XXXXXX",
  "resourceGroup": "mnx387-2-sandbox",
  "securityGroupName": "k8s-default-nsg",
  "securityGroupResourceGroup": "mnx387-2-sandbox",
  "location": "eastus",
  "vmType": "vmss",
  "vnetName": "k8s-vnet",
  "vnetResourceGroup": "mnx387-2-sandbox",
  "subnetName": "k8s",
  "routeTableName": "routes",
  "loadBalancerSku": "Standard",
  "cloudProviderBackoff": true,
  "cloudProviderBackoffRetries": 6,
  "cloudProviderBackoffExponent": 1.5,
  "cloudProviderBackoffDuration": 5,
  "cloudProviderBackoffJitter": 1,
  "cloudProviderRatelimit": true,
  "cloudProviderRateLimitQPS": 3,
  "cloudProviderRateLimitBucket": 10,
  "maximumLoadBalancerRuleCount": 250,
  "useManagedIdentityExtension": true,
  "useInstanceMetadata": true,
  "disableOutboundSnat": true,
  "preConfiguredBackendPoolLoadBalancerTypes": "external",
  "primaryScaleSetName": "k8s-sbox-mnx387-2-nodes-0330",
  "loadBalancerBackendPoolConfigurationType": "nodeIP",
  "multipleStandardLoadBalancerConfigurations": [
    {
      "name": "kubernetes",
      "primaryVMSet": "k8s-sbox-mnx387-2-nodes-0330"
    },
    {
      "name": "k8s-sbox-mnx387-2-ingress2-nodes-0327",
      "primaryVMSet": "k8s-sbox-mnx387-2-ingress2-nodes-0327",
      "serviceLabelSelector": {
        "matchLabels": {
          "dedicatedlb": "k8s-sbox-mnx387-2-ingress2-nodes-0327"
        }
      }
    },
    {
      "name": "k8s-sbox-mnx387-2-mediabptt-nodes-0327",
      "primaryVMSet": "k8s-sbox-mnx387-2-mediabptt-nodes-0327",
      "serviceLabelSelector": {
        "matchLabels": {
          "dedicatedlb": "k8s-sbox-mnx387-2-mediabptt-nodes-0327"
        }
      }
    },
    {
      "name": "k8s-sbox-mnx387-2-radios-nodes-0327",
      "primaryVMSet": "k8s-sbox-mnx387-2-radios-nodes-0327",
      "serviceLabelSelector": {
        "matchLabels": {
          "dedicatedlb": "k8s-sbox-mnx387-2-radios-nodes-0327"
        }
      }
    }
  ]
}

  **VMSSs and load balancers having the same name:**
    k8s-sbox-mnx387-2-ingress2-nodes-0327
    k8s-sbox-mnx387-2-mediabptt-nodes-0327
    k8s-sbox-mnx387-2-radios-nodes-0327

- Others:
**- Sanitized screenshot from Portal:**
image

**Example of a working cofig**
{
  "etag": "W/\"XXXXXX\"",
  "id": "/subscriptions/XXXXXX/resourceGroups/mnx387-2-sandbox/providers/Microsoft.Network/loadBalancers/k8s-sbox-mnx387-2-mediabptt-nodes-0327/backendAddressPools/monitoring-cie-infra-debug-service-dedicated-lb-mediabptt",
  "loadBalancerBackendAddresses": [
    {
      "ipAddress": "XXXXXX",
      "name": "k8s-sbox-mnx387-2-mediabptt-nodes-0327000001"
    },
    {
      "ipAddress": "XXXXXX",
      "name": "k8s-sbox-mnx387-2-mediabptt-nodes-0327000000"
    }
  ],
  "loadBalancingRules": [
    {
      "id": "/subscriptions/XXXXXX/resourceGroups/mnx387-2-sandbox/providers/Microsoft.Network/loadBalancers/k8s-sbox-mnx387-2-mediabptt-nodes-0327/loadBalancingRules/afc102b4bf54c4ea2b1e885eecdf12df-TCP-8080",
      "resourceGroup": "mnx387-2-sandbox"
    }
  ],
  "name": "monitoring-cie-infra-debug-service-dedicated-lb-mediabptt",
  "provisioningState": "Succeeded",
  "resourceGroup": "mnx387-2-sandbox",
  "type": "Microsoft.Network/loadBalancers/backendAddressPools",
  "virtualNetwork": {
    "id": "/subscriptions/XXXXXX/resourceGroups/mnx387-2-sandbox/providers/Microsoft.Network/virtualNetworks/k8s-vnet",
    "resourceGroup": "mnx387-2-sandbox"
  }
}

**Example of a new service of type LB that fails…missing the VNet config for some reason?**

{
  "etag": "W/\"XXXXXX\"",
  "id": "/subscriptions/XXXXXX/resourceGroups/mnx387-2-sandbox/providers/Microsoft.Network/loadBalancers/k8s-sbox-mnx387-2-radios-nodes-0327/backendAddressPools/monitoring-cie-infra-debug-service-dedicated-lb-radios",
  "loadBalancerBackendAddresses": [
    {
      "ipAddress": "XXXXXX",
      "name": "k8s-sbox-mnx387-2-radios-nodes-0327000000"
    },
    {
      "ipAddress": "XXXXXX",
      "name": "k8s-sbox-mnx387-2-radios-nodes-0327000001"
    }
  ],
  "loadBalancingRules": [
    {
      "id": "/subscriptions/XXXXXX/resourceGroups/mnx387-2-sandbox/providers/Microsoft.Network/loadBalancers/k8s-sbox-mnx387-2-radios-nodes-0327/loadBalancingRules/abf42a3fc91b748a0b91139c490cc4fe-TCP-8080",
      "resourceGroup": "mnx387-2-sandbox"
    }
  ],
  "name": "monitoring-cie-infra-debug-service-dedicated-lb-radios",
  "provisioningState": "Succeeded",
  "resourceGroup": "mnx387-2-sandbox",
  "type": "Microsoft.Network/loadBalancers/backendAddressPools"
}

### PR DESCRIPTION
**Pull request by nilo19**
… reconciliation loops

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

We need to ensure that the vnet ID is attached to the backend pool in the local service reconciliation loops.
This happens in a rare corner case where the user updates from legacy multi-slb to the current new design of multi-slb. In this case, the backend pool may not have vnet ID attached and the update backend pool request will return an error.

#### Which issue(s) this PR fixes:

Fixes #6172

#### Does this PR introduce a user-facing change?

```release-note
fix: Ensure vnet ID will be attached to backend pool in local service reconciliation loops.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/provider/azure_loadbalancer_backendpool.go [hunk 1]
```diff
@@ -792,6 +796,23 @@ func newBackendPool(lb *network.LoadBalancer, isBackendPoolPreConfigured bool, p
 }
 
 func (az *Cloud) addNodeIPAddressesToBackendPool(backendPool *network.BackendAddressPool, nodeIPAddresses []string) bool {
```
Comment (nilo19) [inline pkg/provider/azure_loadbalancer_backendpool.go:798]: This func is used in both cluster and local svc reconciliations, so move the vnet code to here.

**Comment by nilo19** [comment]
@nidomoko please try this fix if you need to do it quickly by building an image against this commit, or you can expect our next minor version release.
