### PR TITLE
fix: fix duplicate podCIDR allocation when node patch request fails

### LINKED ISSUE #4556: node ipam may assign same podCIDR to multiple nodes when podCIDR patch fails
#### What happened:
When node podCIDR patch fails due to some reason, node ipam controller may assign the same podCIDR to multiple nodes. In range allocator, nodeCIDRUpdate worker releases an allocated podCIDR when node podCIDR patch fails, then it retries without requesting a new one. So multiple nodes may have the same podCIDR.

#### What you expected to happen:
node ipam controller should assign each node a unique podCIDR range.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by jwtty**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
When node podCIDR patch request fails, we release the allocated CIDR but retry without claiming new ones. This PR fixes the issue by re-allocating new CIDR when updateNodeCIDR is retried.

#### Which issue(s) this PR fixes:

Fixes #4556 

#### Does this PR introduce a user-facing change?

```release-note
Fix possible duplicate podCIDR allocation when node podCIDR patch request fails.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/nodeipam/ipam/range_allocator.go [hunk 1]
```diff
@@ -327,21 +324,55 @@ func filterOutServiceRange(clusterCIDRs []*net.IPNet, cidrSets []*cidrset.CidrSe
 	}
 }
 
+func (r *rangeAllocator) allocatePodCIDRs() ([]*net.IPNet, error) {
+	allocatedCIDRs := make([]*net.IPNet, len(r.cidrSets))
+	for idx := range r.cidrSets {
+		podCIDR, err := r.cidrSets[idx].AllocateNext()
+		if err != nil {
```
Comment (nilo19) [inline pkg/nodeipam/ipam/range_allocator.go:331]: The AllocateNext would be a dummy operation if failed so no need to release cidrs here? https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/nodeipam/ipam/cidrset/cidr_set.go#L214

Comment (jwtty) [reply pkg/nodeipam/ipam/range_allocator.go:331]: But we need to release ips from cidrSet[0] to cidrSet[idx - 1]?

**Comment by feiskyer** [comment]
This should be backported to stable releases.

/cherrypick release-1.28
