### PR TITLE
fix: ignore Windows 2019 in `ensureVMSSInPool` for IPv6 backend pools only

### LINKED ISSUE #6315: IPv6 LoadBalancer backend pools should always ignore Windows 2019 VMSS
#### What happened:

It is possible for 1P customers to run dual-stack clusters with Windows 2019 node pools. The Windows 2019 nodes are not configured with IPv6 from the CNI perspective and will never get IPv6 support.

When a new service is added (IPv4 or IPv6) in a cluster with this mixed-mode configuration, the LB cannot be reconciled because cloud-provider will throw this error `"failed to find a primary IP configuration (IPv6=true) for the VMSS VM or VMSS`.

#### What you expected to happen:

cloud-provider should skip 2019 VMSS instances when reconciling the IPv6 backend pool.

#### How to reproduce it (as minimally and precisely as possible):

1. Create a dual-stack `--ip-families ipv4,ipv6` AKS cluster with a Windows 2019 node pool.
2. create a k8s service with `type=LoadBalancer`

#### Anything else we need to know?:

I'm open to other ideas here. Could we support a label that excludes nodes from _specific_ LB backend pools?

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): dual-stack cni overlay
- Others:

### PR DESCRIPTION
**Pull request by tyler-lloyd**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

doesn't try to add Windows  2019 VMSS to IPv6 backend pools because 2019 will never support IPv6 so it shouldn't be added.

#### Which issue(s) this PR fixes:

Fixes #6315 

#### Does this PR introduce a user-facing change?

```release-note
This only affects 1P, internal-to-Microsoft, customers. Windows 2019 with dual-stack is not possible otherwise.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nilo19** [comment]
does it affect ip-based pool?

**Comment by tyler-lloyd** [comment]
> does it affect ip-based pool?

maybe? I'm not as familiar with ip-based pools. do customers have to opt-in to use that feature? would there be an error if someone is using ip pools but the VM has no IPv6 IP? if yes, then we'd want to also have the same exclusion for Windows2019 nodes as I'm doing in this PR.

File: pkg/provider/azure_vmss.go [hunk 1]
```diff
@@ -1309,6 +1317,46 @@ func (ss *ScaleSet) ensureVMSSInPool(_ *v1.Service, nodes []*v1.Node, backendPoo
...
+	storageProfile := vmss.VirtualMachineProfile.StorageProfile
+
+	if storageProfile.OsDisk == nil || storageProfile.OsDisk.OsType != compute.OperatingSystemTypesWindows {
+		return false
+	}
+
+	if storageProfile.ImageReference == nil || storageProfile.ImageReference.ID == nil {
+		return false
+	}
+	// example: /subscriptions/109a5e88-712a-48ae-9078-9ca8b3c81345/resourceGroups/AKS-Windows/providers/Microsoft.Compute/galleries/AKSWindows/images/windows-2019-containerd/versions/17763.5820.240516
```
Comment (lzhecheng) [inline pkg/provider/azure_vmss.go:1339]: Let's hide the sub info.

File: pkg/provider/azure_vmss_test.go [hunk 2]
```diff
@@ -2262,6 +2262,7 @@ func TestEnsureVMSSInPool(t *testing.T) {
 		vmSetName             string
 		clusterIP             string
 		nodes                 []*v1.Node
+		mutate                func(compute.VirtualMachineScaleSet)
```
Comment (lzhecheng) [inline pkg/provider/azure_vmss_test.go:2265]: I think this `mutate()` is to turn a linux vmss to a windows one, but it doesn't seem clear with just "mutate" as a variable name. Then I suggest a better one:
1. create a `buildTestWindowsVMSSWithLB()` and in this func, call `buildTestVMSSWithLB()` and mutate there
2. use a `isWindows2019` variable instead here, then in this test func L2556, create a vmss with `buildTestVMSSWithLB()` or `buildTestWindowsVMSSWithLB()`

File: pkg/provider/azure_vmss.go (hunk 1 above)
Comment (tyler-lloyd) [reply pkg/provider/azure_vmss.go:1339]: that's fine, but this is the public sub that all AKS customers can see if they look at their imageRef on the MC.

File: pkg/provider/azure_vmss_test.go (hunk 2 above)
Comment (tyler-lloyd) [reply pkg/provider/azure_vmss_test.go:2265]: hm, `mutate` allows the test writer to change any property they want so that we don't have to keep adding more params to BuildTest*() funcs. this makes things more extensible. but I don't mind changing it to have explicit windows semantics.

Comment (tyler-lloyd) [reply pkg/provider/azure_vmss_test.go]: okay, refactored in https://github.com/kubernetes-sigs/cloud-provider-azure/pull/6316/commits/621d00871ede291ac367cbfae1b1bc5157e9eeb1

File: pkg/provider/azure_vmss.go (hunk 1 above)
Comment (tyler-lloyd) [reply pkg/provider/azure_vmss.go]: updated

File: pkg/provider/azure_vmss.go [hunk 3]
```diff
@@ -1309,6 +1317,46 @@ func (ss *ScaleSet) ensureVMSSInPool(_ *v1.Service, nodes []*v1.Node, backendPoo
...
+	if len(parts) < 4 {
+		return false
+	}
+
+	imageName := parts[len(parts)-3]
+	if !strings.EqualFold(imageName, consts.VmssWindows2019ImageGalleryName) {
+		return false
+	}
+
+	osVersion := strings.Split(parts[len(parts)-1], ".")
```
Comment (nilo19) [inline pkg/provider/azure_vmss.go:1351]: Can we parse the string by regexp, to get rid of those Split?
