### PR TITLE
Aggregate overlapping allowed source ranges

### LINKED ISSUE #6775: OverlappingSubnetsNotPermittedInSecurityRule occurs when using overlapping CIDR as allowed source ranges
#### What happened:

OverlappingSubnetsNotPermittedInSecurityRule occurs when using overlapping CIDR blocks as allowed source ranges.

#### What you expected to happen:

no error

#### How to reproduce it (as minimally and precisely as possible):

set overlap CIDR in `spec.LoadBalancerSourceRanges` or `annotation: service.beta.kubernetes.io/azure-allowed-ip-ranges`

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: conflict
  annotations:
    service.beta.kubernetes.io/azure-allowed-ip-ranges: "10.0.0.0/8,10.0.0.0/16" // overlap
spec:
  type: LoadBalancer
  selector:
    app: conflict
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: tcp
    port: 4000
    protocol: TCP
    targetPort: 4000
```

#### Anything else we need to know?:

It’s because of the change made in #5164, and it’s only going to impact clusters with version >= 1.29.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by zarvd**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This PR introduces a prefix tree to aggregate overlapping allowed source ranges. Without it, customers have to merge the CIDR manually; otherwise, the Azure NSG operation will fail.

#### Which issue(s) this PR fixes:

Fixes #6775 

#### Special notes for your reviewer:

```
goos: darwin
goarch: arm64
pkg: sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/iputil
BenchmarkAggregatePrefixes/IPv4-100-10             72164             16502 ns/op  // with 100 IPv4 CIDRs
BenchmarkAggregatePrefixes/IPv6-100-10             71418             16706 ns/op
BenchmarkAggregatePrefixes/IPv4-IPv6-200-10        22771             52537 ns/op
BenchmarkAggregatePrefixes/IPv4-1000-10             7576            160325 ns/op  // with 1k IPv4 CIDRs
BenchmarkAggregatePrefixes/IPv6-1000-10             7062            159379 ns/op
BenchmarkAggregatePrefixes/IPv4-IPv6-2000-10        2426            494645 ns/op
BenchmarkAggregatePrefixes/IPv4-10000-10             537           2214890 ns/op
BenchmarkAggregatePrefixes/IPv6-10000-10             538           2220426 ns/op
BenchmarkAggregatePrefixes/IPv4-IPv6-20000-10        192           6245388 ns/op // with 20k IPv4 + IPv6 CIDRs
BenchmarkPrefixTree_Add/IPv4-10                  8045304               151.6 ns/op
BenchmarkPrefixTree_Add/IPv6-10                  4094680               289.5 ns/op
BenchmarkPrefixTree_List/IPv4-10                  568363              1909 ns/op
BenchmarkPrefixTree_List/IPv6-10                  547520              2339 ns/op
PASS
ok      sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/iputil       18.471s
```

I guess the performance of this operation is acceptable for now. It’s extremely rare to find a service that allows more than 20,000 CIDRs anyway.

#### Does this PR introduce a user-facing change?

```release-note
Aggregate overlapping allowed source ranges
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nilo19** [comment]
Can we add an e2e?

File: tests/e2e/network/network_security_group.go [hunk 1]
```diff
@@ -619,6 +640,21 @@ var _ = Describe("Network security group", Label(utils.TestSuiteLabelNSG), func(
 				allowedIPv6Ranges = []string{
 					"2c0f:fe40:8000::/48", "2c0f:feb0::/43",
 				}
+
+				// The overlapping IP ranges will be aggregated after reconciled
```
Comment (zarvd) [inline tests/e2e/network/network_security_group.go:644]: @nilo19 Added some overlapping CIDRs to the existing cases. Let’s see how it goes.

**Review by feiskyer — APPROVED** [review]
LGTM
