### PR TITLE
Fix node address unable to update issue

### LINKED ISSUE #273: cloud-node-manager failed to update node addresses
**What happened**:

cloud-node-manager failed to update node addresses because of following error:

```sh
I1225 02:06:38.925286       1 nodemanager.go:143] Started cloud-node-manager
E1225 02:06:38.959574       1 nodemanager.go:151] no credentials provided for Azure cloud provider
E1225 02:06:38.959661       1 nodemanager.go:151] no credentials provided for Azure cloud provider
```

This is because cloud-node-manger is trying to update addresses for all nodes:

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/4ea58667d1785f1cb6318c73db4e77d145e981f6/pkg/nodemanager/nodemanager.go#L127-L137

Since no Azure credential would be provided, cloud-node-manger should only update the addresses for the current node.

**What you expected to happen**:

Since no Azure credential would be provided, cloud-node-manger should only update the addresses for the current node.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind bug

**What this PR does / why we need it**:

Fix node address unable to update issue and add a set of unit tests for node manager.

**Which issue(s) this PR fixes**:

Fixes #273 

**Special notes for your reviewer**:

**Release note**:
```
Fix node address unable to update issue
```

### CODE REVIEW

File: pkg/nodemanager/nodemanager.go [hunk 1]
```diff
@@ -61,6 +57,50 @@ type NodeProvider interface {
...
 }
 
+// labelReconcileInfo lists Node labels to reconcile, and how to reconcile them.
+// primaryKey and secondaryKey are keys of labels to reconcile.
+//   - If both keys exist, but their values don't match. Use the value from the
+//   primaryKey as the source of truth to reconcile.
+//   - If ensureSecondaryExists is true, and the secondaryKey does not
+//   exist, secondaryKey will be added with the value of the primaryKey.
+var labelReconcileInfo = []struct {
+	primaryKey            string
```
Comment (andyzhangx) [inline pkg/nodemanager/nodemanager.go]: do you have the design doc about this label reconciler logic?

Comment (feiskyer) [reply pkg/nodemanager/nodemanager.go]: this is same logic from k/k cloud-node-controller. Since some node lables goes to GA, we should do the same for it.

Refer https://github.com/kubernetes/kubernetes/pull/81431.
