### PR TITLE
fix(instance-v2): use false<bool> representing ErrInstanceNotFound<errror>

### LINKED ISSUE #1390: Should assume node is not found than reporting an error in InstanceExists
#### What happened:

If the `InstanceExists` failed to get provider ID due to `instance not found`, we should assume this node is gone than reporting an error here. https://github.com/kubernetes-sigs/cloud-provider-azure/blob/22837509ca53aeb1ba1fc84ebbf6d0ca835b4514/pkg/provider/azure_instances.go#L232-L236

In this case, the node lifecycle controller will delete the not found node as well. https://github.com/kubernetes/cloud-provider/blob/master/controllers/nodelifecycle/node_lifecycle_controller.go#L153

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by lodrem**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #1390 

#### Special notes for your reviewer:

Should add unit tests for interfaces of cloudprovider afterwards.

#### Does this PR introduce a user-facing change?

```release-note
fix InstanceV2.InstanceExists: it should return false<bool> instead of ErrInstanceNotFound<error>
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/provider/azure_instances.go [hunk 1]
```diff
@@ -231,6 +231,10 @@ func (az *Cloud) InstanceExists(ctx context.Context, node *v1.Node) (bool, error
 		var err error
 		providerID, err = cloudprovider.GetInstanceProviderID(ctx, az, types.NodeName(node.Name))
 		if err != nil {
+			if errors.Is(err, cloudprovider.InstanceNotFound) {
```
Comment (feiskyer) [inline pkg/provider/azure_instances.go:234]: Could you also add the same check for L243?

File: pkg/provider/azure_instances.go [hunk 2]
```diff
@@ -298,7 +302,7 @@ func (az *Cloud) InstanceShutdown(ctx context.Context, node *v1.Node) (bool, err
 		providerID, err = cloudprovider.GetInstanceProviderID(ctx, az, types.NodeName(node.Name))
 		if err != nil {
 			// Returns false, so the controller manager will continue to check InstanceExistsByProviderID().
-			if strings.Contains(err.Error(), cloudprovider.InstanceNotFound.Error()) {
+			if errors.Is(err, cloudprovider.InstanceNotFound) {
```
Comment (feiskyer) [inline pkg/provider/azure_instances.go:305]: Could you also add the same check for L314?

File: pkg/provider/azure_instances.go (hunk 1 above)
Comment (lodrem) [reply pkg/provider/azure_instances.go]: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_instances.go#L204-L218

The implementation will not return `InstanceNotFound`, the check seems unnecessary?

File: pkg/provider/azure_instances.go (hunk 2 above)
Comment (lodrem) [reply pkg/provider/azure_instances.go]: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_instances.go#L243-L287
L314 check is unnecessary, too

File: pkg/provider/azure_instances.go [hunk 3]
```diff
@@ -231,6 +231,10 @@ func (az *Cloud) InstanceExists(ctx context.Context, node *v1.Node) (bool, error
 		var err error
 		providerID, err = cloudprovider.GetInstanceProviderID(ctx, az, types.NodeName(node.Name))
 		if err != nil {
+			if strings.Contains(err.Error(), cloudprovider.InstanceNotFound.Error()) {
```
Comment (lzhecheng) [inline pkg/provider/azure_instances.go:234]: Do you think we can use `errors.Is()`? Like here:
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/c6f9190091473cabf094f89de2bb6d93dba20114/pkg/provider/azure_instances.go#L206

Comment (lzhecheng) [reply pkg/provider/azure_instances.go:234]: Please ignore. It is the same style like L301

**Comment by lzhecheng** [comment]
It is possible to add a UT for `InstanceExists()`?

**Comment by lodrem** [comment]
> It is possible to add a UT for InstanceExists()?

Yes! We probably need to add UT for all interfaces of https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/vendor/k8s.io/cloud-provider/cloud.go#L43.

And this PR is a hotfix patch. I would add ut for those interfaces afterward if that's ok?

**Comment by lzhecheng** [comment]
> > It is possible to add a UT for InstanceExists()?
> 
> Yes! We probably need to add UT for all interfaces of https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/vendor/k8s.io/cloud-provider/cloud.go#L43.
> 
> And this PR is a hotfix patch. I would add ut for those interfaces afterward if that's ok?

I think for a hotfix, it is still better to have a simple UT. Then we can file an issue to track UT for all methods. What do you think? @feiskyer

File: pkg/provider/azure_instances.go (hunk 3 above)
Comment (marwanad) [inline pkg/provider/azure_instances.go:234]: why can't we use `error.Is` here?

Comment (marwanad) [reply pkg/provider/azure_instances.go:234]: also when will `GetInstanceProviderId` return `InstanceNotFound`? I don't see that happening in any codepath.

https://github.com/kubernetes/cloud-provider/blob/master/cloud.go#L101-L116

Comment (feiskyer) [reply pkg/provider/azure_instances.go:234]: this is because the error would be wrapped into `fmt.Errorf("failed to get instance ID from cloud provider: %v", err)` inside `cloudprovider.GetInstanceProviderID`.

Comment (lodrem) [reply pkg/provider/azure_instances.go:234]: > why can't we use error.Is here?

https://github.com/kubernetes/cloud-provider/blob/master/cloud.go#L112 use `%v` instead of `%w` which I think [errors.Unwrap](https://pkg.go.dev/errors#Unwrap) could not work.

> also when will GetInstanceProviderId return InstanceNotFound? I don't see that happening in any codepath.

https://github.com/kubernetes/cloud-provider/blob/master/cloud.go#L174-L177 the interface requires the impl should return cloudprovider.InstanceNotFound.
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_instances.go#L376 plz check this impl, it would return `InstanceNotFound`.

**Comment by lodrem** [comment]
UT added. PTAL @feiskyer @lzhecheng

**Review by feiskyer — COMMENTED** [review]
thanks for fixing this issue
/lgtm
/approve

**Comment by MartinForReal** [comment]
<html>
<body>


/test pull-cloud-provider-azure-e2e-ccm-vmss
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by feiskyer** [comment]
seems prow is stuck, let's merge this manually since all tests have passed
