### PR TITLE
fix: Remove managed pip if switched to another pip in a different res…

### LINKED ISSUE #8113: Public IP Address orphaned when updating LoadBalancer type Service to a user-provided PIP from another RG
#### What happened:

Updating an existing LoadBalancer type kubernetes Service to bind it to a user-created PIP does not release the existing PIP when that PIP is in a different resource group

#### What you expected to happen:

The PIP which was previously bound to the service should be released and removed

#### How to reproduce it (as minimally and precisely as possible):

0. Set variables to use in future commands
```
export TEST_RG=test-orphaned-pip
```
1. Create a resource-group to test with
```
az group create \
  --location eastus \
  --resource-group $TEST_RG
```
2. Create an AKS cluster
```
az aks create \
  --resource-group $TEST_RG \
  --name my-cluster \
  --node-count 1 \
  --generate-ssh-keys
```
3. Export cluster credentials to a temporary file and set KUBECONFIG
```
az aks get-credentials \
  --resource-group $TEST_RG \
  --name my-cluster \
  -f /tmp/my-cluster.kubeconfig

export KUBECONFIG=/tmp/my-cluster.kubeconfig
```
4. Create a test loadbalancer service on the cluster
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
spec:
  ports:
  - port: 80
  type: LoadBalancer
EOF
```
5. Observe the service's external IP address is created and assigned
6. Get the cluster's identity principal and note it
```
az aks show \
  --resource-group $TEST_RG \
  --name my-cluster \
  --query "identity.principalId" \
  --output tsv
```
7. Create a PIP in $TEST_RG
```
az network public-ip create \
  --resource-group $TEST_RG \
  --name my-loadbalancer-service
```
8. Get the PIP's ID
```
az network public-ip show \
  --resource-group $TEST_RG \
  --name my-loadbalancer-service \
  --query "id" \
  --output tsv
```
9. Assign the Network Contributor role to the cluster identity principal onto the PIP
```
az role assignment create \
  --assignee <PRINCIPAL_ID> \
  --role "Network Contributor" \
  --scope <PIP_ID>
```
10. Annotate the loadbalancer service so that it is reassigned to our user-created PIP
```
kubectl annotate svc my-loadbalancer-service \
  service.beta.kubernetes.io/azure-load-balancer-resource-group=$TEST_RG \
  service.beta.kubernetes.io/azure-pip-name=my-loadbalancer-service
```
11. Observe that the service has been reconciled and now has our PIP assigned
12. Observe that the original PIP remains untouched in the cluster's node resource group

**Note:** If the user-created PIP is created in the cluster's node resource group, the PIP gets released properly as expected. However according to documentation it is a bad practice to create resources in this RG

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by nilo19**
…ource group

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

We should remove managed pip when the service switches to a different pip in another resource group.

#### Which issue(s) this PR fixes:

Fixes #8113

#### Does this PR introduce a user-facing change?

```release-note
fix: Remove managed pip if switched to another pip in a different resource group
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/provider/azure_publicip_repo.go [hunk 1]
```diff
@@ -227,3 +231,12 @@ func getExpectedPIPFromListByIPAddress(pips []*armnetwork.PublicIPAddress, ip st
 
 	return nil, fmt.Errorf("getExpectedPIPFromListByIPAddress: cannot find public IP with IP address %s", ip)
 }
+
+func getPIPRGFromID(pipIDLower string) (string, error) {
+	re := regexp.MustCompile(strings.ToLower(`/subscriptions/(?:.*)/resourceGroups/(.+)/providers/Microsoft.Network/publicIPAddresses/(?:.*)`))
```
Comment (MartinForReal) [inline pkg/provider/azure_publicip_repo.go:236]: Id is in lower case right?

File: pkg/provider/azure_loadbalancer.go [hunk 2]
```diff
@@ -3357,8 +3374,15 @@ func (az *Cloud) reconcilePublicIP(ctx context.Context, pips []*armnetwork.Publi
 	for _, pip := range pipsToBeDeleted {
 		pipCopy := *pip
 		deleteFuncs = append(deleteFuncs, func() error {
-			klog.V(2).Infof("reconcilePublicIP for service(%s): pip(%s), isIPv6(%v) - deleting", serviceName, *pip.Name, isIPv6)
-			return az.safeDeletePublicIP(ctx, service, pipResourceGroup, &pipCopy, lb)
+			pipID := strings.ToLower((ptr.Deref(pipCopy.ID, "")))
+			rg, err := getPIPRGFromID(pipID)
+			if err != nil {
+				logger.Error(err, "Failed to get resource group from PIP ID", "pip-id", pipID)
```
Comment (feiskyer) [inline pkg/provider/azure_loadbalancer.go:3380]: return err here?

File: pkg/provider/azure_loadbalancer.go [hunk 3]
```diff
@@ -3267,13 +3267,29 @@ func (az *Cloud) ensurePIPTagged(service *v1.Service, pip *armnetwork.PublicIPAd
 
 // reconcilePublicIPs reconciles the PublicIP resources similar to how the LB is reconciled.
 func (az *Cloud) reconcilePublicIPs(ctx context.Context, clusterName string, service *v1.Service, lbName string, wantLb bool) ([]*armnetwork.PublicIPAddress, error) {
+	logger := klog.FromContext(ctx).WithName("reconcilePublicIPs").
+		WithValues("load-balancer", lbName)
```
Comment (feiskyer) [inline pkg/provider/azure_loadbalancer.go:3271]: how about using the same log format for those keys (e.g. loadBalancer, resourceGroup (in the following lines)?

Comment (nilo19) [reply pkg/provider/azure_loadbalancer.go]: done

File: pkg/provider/azure_loadbalancer.go (hunk 2 above)
Comment (nilo19) [reply pkg/provider/azure_loadbalancer.go:3380]: done

**Review by feiskyer — APPROVED** [review]
/lgtm
