### PR TITLE
Node manager should retry when not able to get providerID

### LINKED ISSUE #1155: Node may be registered with empty ProviderId when there is something wrong in IMDS
#### What happened:

When IMDS is not available, Node may be registered with empty ProviderId because there is no retrying in the following logic:

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/bfc511f1ca39f87cf47b064c33d5922ae6ed02f9/pkg/nodemanager/nodemanager.go#L381-L385

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/bfc511f1ca39f87cf47b064c33d5922ae6ed02f9/pkg/nodemanager/nodemanager.go#L430-L442

#### What you expected to happen:

`initializeNode` should retry when ProviderID is empty. This could be done by returning an error in `getNodeModifiersFromCloudProvider()` and then retry when `initializeNode` gets an error when invoking `getNodeModifiersFromCloudProvider`.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by jwtty**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Existing code just logs an error when node manager failed to get `providerID` and leaves the field empty. But in reality,
there are other control-plane components requiring `providerID` to not be empty. So node manager should at least retry
to get `providerID` and report error.

This fix allows node manager try 20 times with a time backoff and panic if still failing. UT is also added. 

#### Which issue(s) this PR fixes:

Fixes #1155 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
Current behavior when node manager not able to get providerID (node manager log):

E0228 03:55:11.893444       1 runtime.go:78] Observed a panic: &fmt.wrapError{msg:"failed to initialize node providertest2-vmss-1000001 at cloudprovider: failed to set node provider id: no credentials provided for Azure cloud provider", err:(*fmt.wrapError)(0xc0002d8a20)} (failed to initialize node providertest2-vmss-1000001 at cloudprovider: failed to set node provider id: no credentials provided for Azure cloud provider)
goroutine 100 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1bfd420, 0xc0002d8a40})
        /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x7d
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x203000})
        /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1bfd420, 0xc0002d8a40})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
k8s.io/apimachinery/pkg/util/runtime.Must(...)
        /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:171
sigs.k8s.io/cloud-provider-azure/pkg/nodemanager.(*CloudNodeController).initializeNode(0xc0001069c0, {0x2195ba8, 0xc000058028}, 0xc000680000)
        /go/src/sigs.k8s.io/cloud-provider-azure/pkg/nodemanager/nodemanager.go:390 +0x77c
sigs.k8s.io/cloud-provider-azure/pkg/nodemanager.(*CloudNodeController).AddCloudNode(0xc0001069c0, {0x2195ba8, 0xc000058028}, {0x1e88040, 0xc000680000})
        /go/src/sigs.k8s.io/cloud-provider-azure/pkg/nodemanager/nodemanager.go:352 +0x1a9
sigs.k8s.io/cloud-provider-azure/pkg/nodemanager.NewCloudNodeController.func1({0x1e88040, 0xc000680000})
       ...
        /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x88
panic: failed to initialize node providertest2-vmss-1000001 at cloudprovider: failed to set node provider id: no credentials provided for Azure cloud provider [recovered]
        panic: failed to initialize node providertest2-vmss-1000001 at cloudprovider: failed to set node provider id: no credentials provided for Azure cloud provider
```

### CODE REVIEW

File: pkg/nodemanager/nodemanager.go [hunk 1]
```diff
@@ -378,9 +378,14 @@ func (cnc *CloudNodeController) initializeNode(ctx context.Context, node *v1.Nod
...
-	nodeModifiers, err := cnc.getNodeModifiersFromCloudProvider(ctx, curNode)
+	var nodeModifiers []nodeModifier
+	err = clientretry.OnError(UpdateNodeSpecBackoff, apierrors.IsNotFound, func() error {
+		nodeModifiers, err = cnc.getNodeModifiersFromCloudProvider(ctx, curNode)
+		return err
+	})
 	if err != nil {
-		utilruntime.HandleError(fmt.Errorf("failed to initialize node %s at cloudprovider: %w", node.Name, err))
+		// Instead of just logging the error, panic and node manager can restart
+		utilruntime.Must(fmt.Errorf("failed to initialize node %s at cloudprovider: %w", node.Name, err))
```
Comment (nilo19) [inline pkg/nodemanager/nodemanager.go:388]: @feiskyer do you think we need a panic here?

File: pkg/nodemanager/nodemanager.go [hunk 2]
```diff
@@ -435,10 +440,10 @@ func (cnc *CloudNodeController) getNodeModifiersFromCloudProvider(ctx context.Co
 				}
 			})
 		} else {
-			// we should attempt to set providerID on node, but
-			// we can continue if we fail since we will attempt to set
-			// node addresses given the node name in getNodeAddressesByName
+			// if we are not able to get node provider id,
+			// we return error here and retry in the caller initializeNode()
 			klog.Errorf("failed to set node provider id: %v", err)
+			return nil, apierrors.NewNotFound(v1.Resource("providerid"), node.Name)
```
Comment (nilo19) [inline pkg/nodemanager/nodemanager.go:446]: Can we change this to a dedicated err msg for get provider id failed?

File: pkg/nodemanager/nodemanager.go (hunk 1 above)
Comment (feiskyer) [reply pkg/nodemanager/nodemanager.go:388]: yes, if it is still failing after a few retries, the container should exist and hence the error would be easily identified by Pod status.

**Review by feiskyer — COMMENTED** [review]
Thanks for the fix.

/lgtm
/approve

**Comment by feiskyer** [comment]
Let's also cherry-pick this to the old releases.
